themoment-team/hellogsm-server-25

src/main/java/team/themoment/hellogsmv3/domain/applicant/entity/AuthenticationCode.java
src/main/java/team/themoment/hellogsmv3/domain/applicant/repo/CodeRepository.java
src/main/java/team/themoment/hellogsmv3/domain/applicant/service/AuthenticateCodeService.java
src/main/java/team/themoment/hellogsmv3/domain/applicant/service/CommonCodeService.java
src/main/java/team/themoment/hellogsmv3/domain/applicant/service/CreateApplicantService.java
src/main/java/team/themoment/hellogsmv3/domain/applicant/service/GenerateCodeService.java
src/main/java/team/themoment/hellogsmv3/domain/applicant/service/ModifyApplicantService.java
src/main/java/team/themoment/hellogsmv3/domain/applicant/service/impl/GenerateCodeServiceImpl.java
src/main/java/team/themoment/hellogsmv3/domain/applicant/service/impl/GenerateTestCodeServiceImpl.java

#24 인증번호 발송 로직을 개선하였습니다.
인증번호 로직에서 인증번호 객체를 여러번 저장하여 객체의 갯수로 최대 발송 갯수를 제한하는 방식에서, count 컬럼을 추가하여 해당 컬럼으로 최대 발송 갯수를 제한하는 방식으로 변경하였습니다.

[applicant] 인증번호 로직에서 사용되는 AuthenticationCode 엔티티 개선

---

src/main/java/team/themoment/hellogsmv3/domain/application/entity/CandidateMiddleSchoolGrade.java
src/main/java/team/themoment/hellogsmv3/domain/application/service/CreateApplicationService.java
src/main/java/team/themoment/hellogsmv3/domain/application/service/ModifyApplicationService.java
src/main/java/team/themoment/hellogsmv3/domain/application/type/EvaluationStatus.java

변경된 원서 도메인의 필드에 맞춰서 원서 셍성, 수정 로직을 변경하였습니다.
- `AbstractPersonalInformation` 엔티티에 누락된 필드인 `guardianPhoneNumber`가 추가되어 원서 생성, 수정 로직에 반영하였습니다.
- `AbstractMiddleSchoolGrade` 의 변경된 필드에 맞춰 생성, 수정 로직을 변경하였습니다.
- `EvaluationStatus`의 필드가 잘못 되어있어 수정하였습니다.
- `CandidateMiddleSchoolGrade`의 필요없는 필드를 제거하였습니다.

[application] 변경된 원서 도메인에 맞춰 원서 생성, 수정 로직 변경

---

src/main/java/team/themoment/hellogsmv3/domain/applicant/controller/ApplicantController.java
src/main/java/team/themoment/hellogsmv3/domain/application/controller/ApplicationController.java
src/main/java/team/themoment/hellogsmv3/domain/auth/controller/AuthenticationController.java
src/main/java/team/themoment/hellogsmv3/global/common/response/ApiResponse.java
src/main/java/team/themoment/hellogsmv3/global/common/response/ApiResponseWrapper.java
src/main/java/team/themoment/hellogsmv3/global/common/response/CommonApiMessageResponse.java
src/main/java/team/themoment/hellogsmv3/global/common/response/CommonApiResponse.java
src/main/java/team/themoment/hellogsmv3/global/exception/GlobalExceptionHandler.java
src/main/java/team/themoment/hellogsmv3/global/exception/model/ExceptionResponseEntity.java
src/main/resources/application.yml

모든 controller에서 response값을 `ResponseEntity<>`에 감싸서 반환하고 있어 해당 부분을 공통화 처리하였습니다.
- `CommonApiMessageResponse` 객체를 두어 기존엔 메시지를 반환할때 Map객체를 넘겨주었지만 해당 객체의 정적 메서드를 통해 response하여 안정성을 높혔습니다.
- controller response값에 `ResponseEntity<>`를 감싸서 반환하는 부분을 controlleradvice에서 처리하도록 하여 종복되는 부분을 제거하였습니다.
- body가 있는 response는 controlleradvice에서 `CommonApiResponse` 객체에 상태코드와 함께 담아 반환해줍니다.
- 만약 `CommonApiMessageResponse` 객체가 반환된다면 `instanceof`로 잡아서 by-pass 해주도록 구현하였습니다.
기존에 `NoHandlerFoundException` 해당 예외를 핸들링하는 메서드가 존재하였는데 해당 예외가 발생하여도 예외가 핸들링되지 않는 현상이 발생하였습니다.
`NoHandlerFoundException` 예외에 대해 조사해보니 아래의 설정이 application.yml에 작성되어 있어야 핸들링 된다고 하여 아래의 내용을 추가하였습니다.
```yml
mvc:
throw-exception-if-no-handler-found: true
web:
resources:
add-mappings: false
```
설정 추가 후에는 잘 핸들링 되는 모습을 확인하였습니다.

[global] response 공통화 작업

---

src/main/java/team/themoment/hellogsmv3/domain/application/controller/ApplicationController.java
src/main/java/team/themoment/hellogsmv3/domain/application/dto/response/AdmissionStatusResDto.java
src/main/java/team/themoment/hellogsmv3/domain/application/dto/response/ApplicationDto.java
src/main/java/team/themoment/hellogsmv3/domain/application/entity/abs/AbstractApplication.java
src/main/java/team/themoment/hellogsmv3/domain/application/service/QueryAllApplicationService.java
src/main/java/team/themoment/hellogsmv3/domain/application/service/QueryApplicationByIdService.java
src/main/java/team/themoment/hellogsmv3/domain/application/type/EvaluationResult.java
src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java

원서 도메인(AbstractApplication)에 심층면접 점수(interviewScore) 추가 및 1, 2차 결과 객체 필드에 점수(score)필드를 추가하였습니다.
- `AbstractApplication` 엔티티에 `interviewScore` 필드를 추가하였습니다.
- 기존에 누락되어있던 `EvaluationResult` 클래스의 `score` 필드를 추가하였습니다.
- 원서 조회, 전체조회 반환값에 `interviewScore` 필드를 추가하였습니다.
- 시큐리티 권한 매핑을 수정하였습니다.
- 내 원서 조회, 원서 조회, 원서 전체 조회시 controller 메서드에서 `ResponseEntity`로 [감싸서 반환하는 부분을 제거하였습니다.](https://github.com/themoment-team/hellogsm-server-v3/pull/37)

[application] 원서 도메인 심층면접 점수 필드 추가 및 EvaluationResult에 누락된 필드 추가

---

src/main/java/team/themoment/hellogsmv3/domain/applicant/service/CreateApplicantService.java
src/main/java/team/themoment/hellogsmv3/domain/auth/entity/Authentication.java

신원 본인인증시 authentication의 provider_id와 provider_name이 바뀌어서 저장되는 오류가 발생하여 해결하였습니다.
- 신원본인인증시 authentication의 role이 APPLICANT로 변경되어 저장되는 로직을 authentication 엔티티 내부의 메서드를 사용하도록 변경하였습니다.

[applicant] 신원본인인증시 authentication의 provider_id와 provider_name이 바뀌는 오류 해결

---

src/main/java/team/themoment/hellogsmv3/domain/application/entity/abs/AbstractApplication.java
src/main/java/team/themoment/hellogsmv3/domain/application/entity/abs/AbstractPersonalInformation.java
src/main/java/team/themoment/hellogsmv3/domain/application/type/EvaluationResult.java

원서 도메인의 enum 타입 필드의 EnumType을 String으로 변경하였습니다
원서 도메인에서 enum 타입의 필드 중 EnumType이 String이 아닌 필드가 존재하였습니다.
JPA에서 `@Enumrated` 어노테이션으로 EnumType을 설정해주지 않으면 기본적으로 `ORDINAL` 속성이 지정됩니다. 이는 enum 속성의 순서를 (정수값) 데이터베이스에 저장하기 때문에 만약에 해당 enum에 필드가 수정된다면 전혀 다른 값이 들어가는 문제가 발생할 수 있기 때문에 `STRING` 속성으로 변경하였습니다.

[application] 원서 도메인 enum 타입 필드 EnumType String으로 변경

---

src/main/java/team/themoment/hellogsmv3/domain/applicant/dto/request/ApplicantReqDto.java
src/main/java/team/themoment/hellogsmv3/domain/applicant/dto/response/FoundApplicantResDto.java
src/main/java/team/themoment/hellogsmv3/domain/applicant/entity/Applicant.java
src/main/java/team/themoment/hellogsmv3/domain/applicant/service/CreateApplicantService.java
src/main/java/team/themoment/hellogsmv3/domain/applicant/service/ModifyApplicantService.java
src/main/java/team/themoment/hellogsmv3/domain/applicant/service/QueryApplicantByIdService.java
src/main/java/team/themoment/hellogsmv3/domain/application/dto/response/GedAdmissionInfoResDto.java
src/main/java/team/themoment/hellogsmv3/domain/application/dto/response/GeneralAdmissionInfoResDto.java
src/main/java/team/themoment/hellogsmv3/domain/application/service/QueryApplicationByIdService.java
src/main/java/team/themoment/hellogsmv3/domain/member/entity/Member.java
src/main/java/team/themoment/hellogsmv3/domain/member/entity/type/Sex.java

성별 column name이 `gender -> sex` 로 변경됨에 따라 성별 enum class 이름도 `Gender -> Sex` 로 변경하였습니다.

[member] 성별 enum class 이름 변경

---

src/main/java/team/themoment/hellogsmv3/domain/applicant/controller/ApplicantController.java
src/main/java/team/themoment/hellogsmv3/domain/applicant/entity/ApplicantAuthenticationCode.java
src/main/java/team/themoment/hellogsmv3/domain/applicant/repo/ApplicantCodeRepository.java
src/main/java/team/themoment/hellogsmv3/domain/applicant/service/AuthenticateCodeService.java
src/main/java/team/themoment/hellogsmv3/domain/applicant/service/CommonCodeService.java
src/main/java/team/themoment/hellogsmv3/domain/applicant/service/CreateApplicantService.java
src/main/java/team/themoment/hellogsmv3/domain/applicant/service/GenerateApplicantCodeService.java
src/main/java/team/themoment/hellogsmv3/domain/applicant/service/GenerateCodeService.java
src/main/java/team/themoment/hellogsmv3/domain/applicant/service/ModifyApplicantService.java
src/main/java/team/themoment/hellogsmv3/domain/applicant/service/QueryApplicantByIdService.java
src/main/java/team/themoment/hellogsmv3/domain/applicant/service/impl/GenerateApplicantCodeServiceImpl.java
src/main/java/team/themoment/hellogsmv3/domain/applicant/service/impl/GenerateApplicantTestCodeServiceImpl.java
src/main/java/team/themoment/hellogsmv3/domain/applicant/service/impl/GenerateCodeServiceImpl.java
src/main/java/team/themoment/hellogsmv3/domain/applicant/service/impl/GenerateTestCodeServiceImpl.java
src/main/java/team/themoment/hellogsmv3/domain/member/controller/MemberController.java
src/main/java/team/themoment/hellogsmv3/domain/member/dto/request/GenerateCodeReqDto.java
src/main/java/team/themoment/hellogsmv3/domain/member/dto/response/FoundMemberResDto.java
src/main/java/team/themoment/hellogsmv3/domain/member/entity/AuthenticationCode.java
src/main/java/team/themoment/hellogsmv3/domain/member/repo/CodeRepository.java
src/main/java/team/themoment/hellogsmv3/domain/member/service/GenerateCodeService.java
src/main/java/team/themoment/hellogsmv3/domain/member/service/QueryMemberByIdService.java
src/main/java/team/themoment/hellogsmv3/domain/member/service/impl/GenerateCodeServiceImpl.java
src/main/java/team/themoment/hellogsmv3/domain/member/service/impl/GenerateTestCodeServiceImpl.java
src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java

인증코드 전송 기능을 추가하였습니다.
- 인증코드 전송, 테스트 전송 API를 개발하였습니다.
기존에 구현되어있는 비즈니스 로직 클래스를 member 도메인으로 복사하였습니다. 이렇게 되면서 두 클래스의 이름이 동일하여 빈 이름이 중복되어 Applicant 도메인에 있는 관련된 클래스의 이름 앞에 Applicant prefix를 붙혀 빈 이름이 겹치지 않게 하였습니다.
위의 작업을 진행하면서 기존 로직의 클래스 네이밍 수정, import를 수정하면서 file changed가 늘어나게 되었습니다.
리뷰를 진행해주실 때 해당 부분은 건너뛰고 member 도메인의 로직을 확인해주시면 감사하겠습니다.

[member] 인증코드 전송 기능 구현

---

src/main/java/team/themoment/hellogsmv3/domain/applicant/controller/ApplicantController.java
src/main/java/team/themoment/hellogsmv3/domain/applicant/service/ApplicantAuthenticateCodeService.java
src/main/java/team/themoment/hellogsmv3/domain/member/controller/MemberController.java
src/main/java/team/themoment/hellogsmv3/domain/member/dto/request/AuthenticateCodeReqDto.java
src/main/java/team/themoment/hellogsmv3/domain/member/service/AuthenticateCodeService.java
src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java

전송된 인증코드를 인증하는 기능을 구현하였습니다.
- 전송한 인증코드를 인증 요청시 `AuthenticationCode`의 `authenticated`컬럼의 값이 true가 되어 추후 작성될 본인인증이 요청이 가능하도록 합니다.
- 기존 로직과 빈 이름이 겹처 빈 등록 충돌이 발생하여 기존 로직 클래스명에 `Applicant~` prefix를 붙혀서 해결해두었습니다.
추후에 개선이 필요해보입니다.

[member] 인증코드 인증 기능 구현

---

src/main/java/team/themoment/hellogsmv3/domain/application/service/QueryApplicationByIdService.java
src/main/java/team/themoment/hellogsmv3/domain/member/dto/response/FoundMemberResDto.java

구 버전의 성별 enum인 `Gender`를 사용하던 곳을 새로운 성별 enum인 `Sex`를 사용하도록 수정하였습니다.

[member] Gender enum 사용처 수정

---

src/main/java/team/themoment/hellogsmv3/domain/member/entity/Member.java
src/main/java/team/themoment/hellogsmv3/global/security/oauth/CustomOauth2UserService.java

개발과정에서 모호한 이름떄문에 헷갈리는 상황이 발생하였고 이를 해결하기 위해 이름을 직관적으로 변경하였습니다.
oauth정보를 기반으로 member를 생성하는 method이름을 `buildNewMember`에서 `buildMemberWithOauthInfo`로 변경하였습니다.

[member] oauth정보 기반 member생성 method 이름 변경

---

src/main/java/team/themoment/hellogsmv3/domain/application/annotation/ApplicationDesiredMajorsValidator.java
src/main/java/team/themoment/hellogsmv3/domain/application/annotation/ApplicationValidDesiredMajors.java
src/main/java/team/themoment/hellogsmv3/domain/application/dto/request/ApplicationReqDto.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/annotation/DesiredMajorsValidator.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/annotation/ValidDesiredMajors.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/controller/OneseoController.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/OneseoReqDto.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/MiddleSchoolAchievement.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/Oneseo.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/OneseoPrivacyDetail.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/type/DesiredMajors.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/MiddleSchoolAchievementRepository.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/OneseoPrivacyDetailRepository.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/OneseoRepository.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoService.java
src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java

원서 추가 기능을 구현하였습니다.
- 원서 추가 기능을 구현하였습니다. 
- `Oneseo` 엔티티의 식별 관계인 `OneseoPrivacyDetail`, `MiddleSchoolAchievement` 엔티티를 생성 후 저장합니다.
- ~~`Oneseo` 엔티티의 `wantedScreening - 희망전형` 컬럼을 삭제하였습니다.~~ 
- 논의 후 희망전형 컬럼을 두기로 결정하였습니다!

[oneseo] 원서 추가 기능 구현

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/controller/OneseoController.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/MiddleSchoolAchievement.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/Oneseo.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/OneseoPrivacyDetail.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/ScreeningChangeHistory.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/MiddleSchoolAchievementRepository.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/OneseoPrivacyDetailRepository.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/OneseoRepository.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/ScreeningChangeHistoryRepository.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoService.java
src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java

내 원서 수정, 원서 수정 기능을 구현하였습니다.
- `/oneseo/me`,`/oneseo/{memberId}` 원서 수정 기능을 구현하였습니다.
- 수정 비즈니스 로직 메서드 파라미터에 `isAdmin` 값으로 어드민 수정 요청을 판별합니다. 어드민은 최종제출한 원서도 수정이 가능합니다.
- `Oneseo` 엔티티와 식별 관계인 `OneseoPrivacyDetail`, `MiddleSchoolAchievement` 엔티티를 조회시 해당 엔티티들은 원서 생성시 필수로 save되는 엔티티이므로 JPARepository에서 Optional로 받아오지 않았습니다.
* `@DynamicUpdate` 어노테이션으로 더티채킹시 변경이 발생하는 컬럼에만 update 쿼리가 나가도록 구현하였습니다.
* 기존 더티채킹은 변경이 발생한 컬럼이 있다면 해당 엔티티의 모든 컬럼에 대해서 update 쿼리를 발생시켰습니다. 위의 어노테이션을 엔티티에 붙혀 변경된 컬럼에 대해서만 update 쿼리하도록 구현하였습니다.

[oneseo] 원서 수정 기능 구현

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/controller/OneseoController.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/MiddleSchoolAchievementReqDto.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/OneseoReqDto.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/EntranceTestFactorsDetail.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/EntranceTestResult.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/MiddleSchoolAchievement.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoService.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoService.java
src/main/java/team/themoment/hellogsmv3/global/common/converter/IntegerListConverter.java
src/main/java/team/themoment/hellogsmv3/global/common/converter/StringListConverter.java

- `EntranceTestFactorsDetail(입학시험 평가요소)` 엔티티 추가 작업을 하였습니다.  
- `MiddleSchoolAchievement(중학교 성취도)` 엔티티 구조 변경을 하였습니다.
<br>
```
엔티티 구조
EntranceTestFactorsDetail
- id
- generalSubjectsScore (일반교과 점수)
- artsPhysicalSubjectsScore (비교과 점수)
- totalSubjectsScore (예체능점수)
- attendanceScore (출석 점수)
- volunteerScore (봉사 점수)
- totalNonSubjectsScore (서류평가 점수)
- score1_1 (직무적성 소양평가 점수)
- score1_2 (심층면접 점수)
- score2_1
- score2_2
- score3_1
- gedTotalScore
- gedMaxScore
- percentileRank
MiddleSchoolAchievement
- oneseo
- achievement1_1
- achievement1_2
- achievement1_2
- achievement1_2
- achievement1_2
- generalSubjects
- newSubjects
- artsPhysicalAchievement
- artsPhysicalSubjects
- absentDays
- attendanceDays
- volunteerTime
- liberalSystem
- freeSemester
- gedTotalScore
- gedMaxScore
```
--- …

[entity] 입학시험 평가요소, 중학교 성취도 엔티티 구성

---

src/main/java/team/themoment/hellogsmv3/domain/application/controller/ApplicationController.java
src/main/java/team/themoment/hellogsmv3/domain/application/service/UpdateApplicationFinalSubmissionService.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/controller/OneseoController.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/Oneseo.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/UpdateFinalSubmissionService.java
src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java

원서 최종제출 기능을 추가하였습니다.
- `/oneseo/v3/final-submission` 원서 최종제출 기능을 추가하였습니다.
- 기존 명세서와 구현에서는 해당 API의 HTTP 메서드가 `PUT`으로 매핑되어 있었는데 하나의 컬럼만 수정하기 때문에 `PATCH` 메서드가 더 적절한것 같아 `PATCH` 메서드로 매핑하였습니다. 의견 부탁드립니다!

[oneseo] 원서 최종제출 기능 추가

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/OneseoReqDto.java

원서 추가, 삭제시 중학교 성적 필드 네이밍을 `transcript` → `middleSchoolAchievement`로 변경하였습니다.

[oneseo] 원서 추가, 수정시 중학교 성적 필드 네이밍 변경

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/EntranceTestFactorsDetail.java

MiddleSchoolAchievement에 검정고시 관련 필드와 EntranceTestFactorsDetail의 필드가 중복되기도 하고 2025 입학 전형에서는 검정고시도 일반교과, 비교과 환산 점수 산출식이 있기 때문에 EntranceTestFactorsDetail에 검정고시 관련 필드를 삭제하였습니다.

[oneseo] EntranceTestFactorsDetail 검정고시 관련 필드 삭제

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/Oneseo.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/OneseoRepository.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/custom/CustomOneseoRepository.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/custom/CustomOneseoRepositoryImpl.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyRealOneseoArrivedYnService.java

실물서류 접수가 완료되면 원서접수번호를 할당하는 로직을 구현하였습니다.
<br>
- 실물서류접수 상태 컬럼인 realOneseoArrivedYn가 YES로 전환 후 접수번호 할당을 합니다.  
- 변경된 접수번호 포맷에 맞게 oneseoSubmitCode 타입을 Long에서 String으로 변경하였습니다.
<br>
**접수번호 매커니즘**
전형별로 prefix를 가집니다.  (ex. A-12)
일반전형 = A- , 특별전형 = B- , 정원외전형 = C- 
번호는 db에서 전형별로 max값을 가져와 1을 더한값을 사용합니다. (해당 쿼리는 queryDsl로 구현)

[oneseo] 원서접수번호 할당 구현

---

src/test/java/team/themoment/hellogsmv3/domain/member/service/CreateMemberServiceTest.java

회원가입 서비스인 `CreateMemberService`의 단위테스트를 작성하였습니다.
test case
- CreateMemberService 클래스의 execute 메소드는 유효한 회원 ID와 요청 데이터가 주어지면 새로운 회원을 생성하고 저장 후 Role을 반환한다
- CreateMemberService 클래스의 execute 메소드는 회원 ID가 유효하지 않으면 ExpectedException을 던진다
<br>

[member] 회원가입 서비스 테스트코드 작성

---

src/test/java/team/themoment/hellogsmv3/domain/member/service/CommonCodeServiceTest.java

인증코드 관련 서비스인 `CommonCodeService`의 단위테스트를 작성하였습니다. 
test case
- CommonCodeService 클래스의 validateAndDelete 메소드는 유효한 회원 ID와 코드와 전화번호가 주어지면 코드를 삭제한다
- CommonCodeService 클래스의 validateAndDelete 메소드는 인증 코드가 존재하지 않으면 ExpectedException을 던진다
- CommonCodeService 클래스의 validateAndDelete 메소드는 인증코드가 인증받지 않았다면 ExpectedException을 던진다
- CommonCodeService 클래스의 validateAndDelete 메소드는 잘못된 코드가 주어지면 ExpectedException을 던진다
- CommonCodeService 클래스의 validateAndDelete 메소드는 잘못된 전화번호가 주어지면 ExpectedException을 던진다
<br>

[member] 인증코드 관련 서비스 테스트코드 작성

---

src/test/java/team/themoment/hellogsmv3/domain/member/service/QueryMemberByIdServiceTest.java

지원자 정보 조회 서비스인 `QueryMemberByIdServic`의 단위테스트를 작성하였습니다.
test case
- QueryMemberByIdService 클래스의 execute 메소드는 존재하는 회원 ID가 주어지면 회원 정보를 반환한다.
- QueryMemberByIdService 클래스의 execute 메소드는존재하지 않는 회원 ID가 주어지면 ExpectedException을 던진다. 
<br>

[member] 지원자 정보 조회 서비스 테스트코드 작성

---

src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/SearchOneseoServiceTest.java

원서 정보 검색 서비스인 `SearchOneseoService`의 단위테스트를 작성하였습니다.
test case
- SearchOneseoService 클래스의 execute 메소드는 검색 결과가 없을 때 빈 결과를 반환한다
- SearchOneseoService 클래스의 execute 메소드는 필터링 조건에 따라 적절한 데이터를 반환한다
<br>

[oneseo] 원서 정보 검색 서비스 테스트코드 작성

---

src/test/java/team/themoment/hellogsmv3/domain/member/QueryMemberAuthInfoByIdServiceTest.java
src/test/java/team/themoment/hellogsmv3/domain/member/service/QueryMemberAuthInfoByIdServiceTest.java

- 회원 인증 정보 조회 테스트 코드 작성
1. 존재하는 회원 id가 주어질 경우 회원인증 정보 반환
2. 존재하지 않는 회원 id가 주어진 경우 ExpectedException을 Throw

[member] 회원 인증 정보 조회 테스트코드 추가

---

src/main/java/team/themoment/hellogsmv3/domain/member/entity/AuthenticationCode.java
src/main/java/team/themoment/hellogsmv3/domain/member/service/GenerateCodeService.java
src/test/java/team/themoment/hellogsmv3/domain/member/service/impl/GenerateCodeServiceImplTest.java
src/test/java/team/themoment/hellogsmv3/domain/member/service/impl/GenerateTestCodeServiceImplTest.java

인증코드 전송 관련 서비스 로직의 테스트코드를 추가하였습니다.
`GenerateCodeServiceImpl` 인증코드 전송, `GenerateTestCodeServiceImpl` 인증코드 테스트 전송에 관련된 테스트코드를 작성하였습니다.
`GenerateCodeServiceImpl`
- 유효한 요청이 주어지면
- 새로운 인증코드를 생성하고 저장
- 요청 제한 횟수를 초과한다면
- 예외를 던짐
`GenerateTestCodeServiceImpl`
- 유효한 요청이 주어지면
- 새로운 인증코드를 생성하고 저장 (테스트 전송이기 때문에 count는 0회)

[member] 인증코드 전송 서비스 테스트코드 추가

---

src/test/java/team/themoment/hellogsmv3/domain/member/service/CommonCodeServiceTest.java
src/test/java/team/themoment/hellogsmv3/domain/member/service/CreateMemberServiceTest.java

`CreateMemberServiceTest`와 `CommonCodeServiceTest`의 setUp 과정에서 발생하는 오류 해결

[member] 테스트코드 셋업과정에서 발생하는 오류 해결

---

src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateGedServiceTest.java
src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateGradeServiceTest.java

중학교, 검정고시 성적 환산 서비스 로직 테스트코드를 추가하였습니다.
중학교 성적 환산 서비스 로직
- 올바른 graduationType이 주어졌다면
- 성적을 환산하고 저장합니다.
- 졸업예정자라면 올바른 내신 성적을 환산하고 결과를 저장합니다.
- 졸업자라면 올바른 내신 성적을 환산하고 결과를 저장합니다.
- graduationType이 올바르지 않다면
- 예외를 던집니다.
검정고시 성적 환산 서비스 로직
- 올바른 graduationType이 주어졌다면
- 성적을 환산하고 저장합니다.
- 검정고시 지원자라면 올바른 내신 성적을 환산하고 결과를 저장합니다.
- graduationType이 올바르지 않다면
- 예외를 던집니다.

[oneseo] 성적 환산 서비스 로직 테스트코드 추가

---

build.gradle

스프링부트 3.xx 버전에 맞도록 QueryDSL Qclass 생성 및 재생성 관련 코드를 수정하여, 지속적으로 발생하는 Qclass 재생성 관련 문제를 해결하였습니다.

[global] 스프링부트 3.xx 버전에 맞도록 QueryDSL 설정 변경하여 오류 해결

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoService.java
src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoServiceTest.java

원서 수정 서비스 로직의 테스트코드를 추가하였습니다.
- 유효한 데이터가 주어진 상황이라면
- 기존의 원서 엔티티를 수정하고 저장합니다.
- 전형이 변경되었다면 히스토리를 저장합니다.
- 회원 id가 유효하지 않다면
- 예외를 발생시킵니다.
- 기존 원서 엔티티가 존재하지 않는다면
- 예외를 발생시킵니다.
- 기존 원서 엔티티가 최종제출되었다면
- 예외를 발생시킵니다.

[oneseo] 원서 수정 서비스 테스트코드 추가

---

src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyInterviewScoreServiceTest.java

심층면점 점수 기입 서비스 로직 테스트코드를 작성하였습니다.
- memberId로 회원을 찾을 수 없는 경우
- ExpectedException을 던진다
- memberId로 조회한 member 엔티티로 원서를 찾을 수 없는 경우
- ExpectedException을 던진다
- 해당 원서의 입학시험결과 엔티티를 찾을 수 없는 경우
- ExpectedException을 던진다
- 모든 유효성 검사를 통과했다면
- 변경된 심층면점점수를 수정하고 저장한다

[oneseo] 심층면점 점수 기입 서비스 로직 테스트 코드 추가

---

src/test/java/team/themoment/hellogsmv3/domain/thirdParty/service/UploadImageServiceTest.java

이미지 업로드 기능 테스트코드 작성
1. 파일이 존재하지 않을 경우 ExpectedException을 던진다.
2. 유효하지 않은 확장자를 가진 파일이 주어지면 ExpectedException을 던진다.
3. 유효한 파일이 주어지면 S3에 업로드된 파일의 URL을 반환한다.
4. 유효하지 않은 파일을 업로드할 경우 RuntimeException을 던진다.

[thirdParty] 이미지 업로드 기능 테스트코드 작성

---

src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/DeleteOneseoServiceTest.java

원서 삭제 테스트코드 작성
1.존재하는 ID가 주어지면 원서가 최종 제출되지 않았으면 삭제한다.
2.존재하는 ID가 주어지면 원서가 최종 제출 되었으면 ExpectedException을 던진다.
3.존재하지 않는 회원 ID가 주어지면 ExpectedException을 던진다.

[oneseo] 원서 삭제 테스트코드 작성

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/EntranceTestResultRepository.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyAptitudeEvaluationScoreService.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyInterviewScoreService.java
src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyAptitudeEvaluationScoreServiceTest.java

적성 검사 점수 기입 테스트 코드 작성
1. 존재하는 회원 ID와 적성 검사 점수가 주어지면 적성 검사 점수를 저장한다.
2. 존재하지 않는 회원 ID가 주어지면 ExpectedException을 던진다.

[oneseo] 적성 검사 점수 기입 테스트 코드 작성

---

src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyRealOneseoArrivedYnServiceTest.java

실물 원서 제출 여부 변경 테스트 코드 작성
1. 존재하는 회원 ID가 주어지면 원서 도착 여부를 전환하고, 해당 정보를 반환한다.
2. 존재하지 않는 회원 ID가 주어지면 ExpectedException을 던진다.

[oneseo] 실물 원서 제출 여부 변경 테스트 코드 작성

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/MiddleSchoolAchievementReqDto.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/response/MiddleSchoolAchievementResDto.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/MiddleSchoolAchievement.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateGedService.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoService.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoService.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/OneseoTempStorageService.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/QueryOneseoByIdService.java
src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateGedServiceTest.java
src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoServiceTest.java
src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoServiceTest.java
src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/QueryOneseoByIdServiceTest.java

비즈니스 요구사항 변경으로 인해 `검정고시 만점` 필드는 고정값으로 변경됨에 따라 변경사항들을 반영하였습니다.
- MiddleSchoolAchievement 테이블의 `gedMaxScore` 컬럼 삭제
- dto에서 `gedMaxScore`  필드 삭제
- 위의 변경사항에 따른 추가 변경사항, 테스트 코드 수정
- 작업을 진행하면서 검정고시 환산식에 소수점이  맞지 않아 계산이 제대로 진행되지 않는 부분이 있어 수정하였습니다.

fix(oneseo): 검정고시 환산식 소수점 수정

---

src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyInterviewScoreServiceTest.java

심층 면접 점수 기입 서비스로직 테스트코드를 작성하였습니다.

[oneseo] 심층 면접 점수 기입 서비스로직 테스트코드 추가

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/Oneseo.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/custom/CustomOneseoRepository.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/custom/impl/CustomOneseoRepositoryImpl.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/SearchOneseoService.java
src/main/resources/application.yml
src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/SearchOneseoServiceTest.java

N+1 문제가 발생하던 원서 조회 기능을 개선하였습니다.
`Oneseo`엔티티와 `OneseoPrivacyDetail`, `EntranceTestResult`엔티티는 1:1 연관관계로 매핑되어있습니다.
기존 원서 검색시에는 `Oneseo`엔티티를 조회 후 map으로 순회하며 `OneseoPrivacyDetail`, `EntranceTestResult`엔티티를 조회하였습니다. 이런 방식은 1 (root = oneseoes) + 2N (OneseoPrivacyDetail, EntranceTestResult) 만큼의 추가 쿼리가 발생하므로 성능 저하가 발생합니다.
`Oneseo` 엔티티에서 `OneseoPrivacyDetail`, `EntranceTestResult` 엔티티에 대한 양방향 연관관계를 만들어 fetch join하여 문제를 해결하였습니다. 하지만 세 엔티티를 페치조인하니 select 절의 컬럼 수가 상당히 많아졌습니다. (30개)
페치조인보다 일반조인을 하여 원서 검색시 필요한 필드만 조회하는것이 더 성능이 좋을것이라 생각하여 프로젝션을 적용하여 필요한 필드 가져와 DTO로 바로 조회하는 방법을 선택하였습니다.
최종적으로 원서 검색을 쿼리 1번으로 최적화 하였고 프로젝션을 적용하여 필요한 필드만 조회하도록 개선하였습니다.

[oneseo] 원서 검색 N+1 문제 개선, 프로젝션 적용

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/custom/impl/CustomOneseoRepositoryImpl.java

원서 검색시 `totalElements - 총 원서 개수` 필드가 모든 페이지의 총 원서 개수가 아닌 현재 페이지의 원서 개수를 출력하는 이슈가 있어 해결하였습니다.
- 기존에는 검색된 페이지의 원서 size를 `totalElements` 값으로 설정하였습니다. 해당 부분을 count 쿼리 메서드를 추가하여 검색 조건에 맞는 모든 원서의 개수를 `totalElements` 값으로 설정하도록 변경하였습니다.
- `PageableExecutionUtils` 클래스를 활용하여 count 쿼리가 필요없는 상황에서는 count 쿼리를 날리지 않도록 최적화 하였습니다.
- count 쿼리가 필요없는 상황: 컨텐츠 사이즈가 페이지 사이즈 보다 작을때, 마지막 페이지일때

[oneseo] 원서 검색 총 원서 개수 조회 로직 수정

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/custom/impl/CustomOneseoRepositoryImpl.java

원서 검색 쿼리에서 잘못된 조건이 걸리는 부분이 존재하여 수정하였습니다.
원서 검색 쿼리인 `findAllByKeywordAndScreeningAndSubmissionStatusAndTestResult` 메서드의 where절을 build하는 부분에서 `FALL` case에 대해 1차시험결과에 대한 조건만 걸고 있었습니다.   
`andAnyOf`를 통해 1,2차 중 하나라도 FALL인 유저가 필터링되도록 수정하였습니다.

[oneseo] 원서 검색 쿼리 잘못된 조건 수정

---

src/main/java/team/themoment/hellogsmv3/global/config/PropertiesScanConfig.java
src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java
src/main/java/team/themoment/hellogsmv3/global/security/data/ScheduleEnvironment.java
src/main/java/team/themoment/hellogsmv3/global/security/filter/TimeBasedFilter.java
src/main/resources/application.yml

특정 기간에만 사용 사능한 API 검증용 custom filter를 추가하였습니다.
입학요강을 바탕으로  원서 임시저장, 원서 저장, 내 원서 조회, 증명사진 등록하기 기능을 `10월 14일 09:00` ~ `10월 17일 17:00` 해당 기간 사이에만 사용 가능하도록 TimeBasedFilter를 구현하였습니다.
`TimeBasedFilter`에 startTime, endTime을 env로 받아 `SecurityConfig`에서 기간을 제한할 API url, method를 등록시켜 특정 기간 이외의 시간에 요청을 보내면 403 예외를 발생시키도록 구현하였습니다.
> application.yml 파일이 변경되어 노션을 참고하여 로컬 환경에 반영 부탁드립니다.

[global] 특정 기간에만 사용 사능한 API 검증용 custom filter 추가

---

build.gradle
src/main/java/team/themoment/hellogsmv3/domain/member/service/SendCodeNotificationService.java
src/main/java/team/themoment/hellogsmv3/domain/member/service/impl/GenerateCodeServiceImpl.java
src/main/java/team/themoment/hellogsmv3/global/thirdParty/aws/sns/SendSmsService.java
src/main/java/team/themoment/hellogsmv3/global/thirdParty/aws/sns/impl/SendCodeNotificationServiceImpl.java
src/main/java/team/themoment/hellogsmv3/global/thirdParty/aws/sns/impl/SendSmsServiceImpl.java
src/main/java/team/themoment/hellogsmv3/global/thirdParty/aws/sns/template/AwsCallBack.java
src/main/java/team/themoment/hellogsmv3/global/thirdParty/aws/sns/template/AwsTemplate.java
src/main/resources/application.yml

인증번호 전송 로직을 aws sns에 연동하여 인증번호 문자 전송 기능을 구현하였습니다.
- `SendCodeNotificationService`를 구현하여 기존 `GenerateCodeServiceImpl`에서 생성된 인증번호를 aws sns를 통해 문자메시지로 전송하도록 연동하였습니다.
- 한국 region에서는 aws sns에서 문자 메시지 전송 기능을 지원하지 않아 작년 구현과 같이 도쿄 region을 사용하였습니다.
- 메시지는 총 두번으로 나누어 발송됩니다. (인증번호 content & 면책조항 footer) 한번 발송시 두번의 메시지가 발송되기 때문에 1회 발송시 비용은 약 `0.02414 * 2 = 0.04828USD`으로 약 65.68원이 발생합니다.

[member] 인증번호 전송 기능 aws sns 연동

---

src/test/java/team/themoment/hellogsmv3/domain/member/service/impl/GenerateCodeServiceImplTest.java

#122 해당 PR에서 `GenerateCodeServiceImpl` 클래스에 변경사항이 테스트코드에 반영되지 않아 CI 도중 오류가 발생하여 수정하였습니다.
`GenerateCodeServiceImpl` 클래스에서 새롭게 추가된 기능인 `SendCodeNotificationService`을 목 객체로 주입받는 부분과 해당 클래스의 메서드를 정상적으로 호출하는지 테스트하는 코드를 추가하였습니다.

[test] 인증코드 전송 테스트코드 수정

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/EntranceTestResult.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/ScreeningChangeHistory.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoService.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoService.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/OneseoService.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/OneseoTempStorageService.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/QueryOneseoByIdService.java

원서 관련 redis 캐시에서 문제가 발생하여 개선해보았습니다. 원서 관련 테이블의 컬럼명 설정이 잘못 되어있어 수정하였습니다.
- 현재 원서 임시 저장시 캐시 생성, 원서 조회시 캐시 확인으로 캐싱이 적용되어 있습니다. 하지만 원서 조회시 캐싱을 적용하는 `@Cacheable` 어노테이션은 캐시가 없다면 response 값을 redis에 캐싱합니다.
어드민 권한을 가진 유저는 특정 사용자의 원서를 수정할 수 있는데 수정 메서드에는 캐시 관련 설정이 되어있지 않습니다. 그렇기 때문에 만약 원서 생성 후 원서 조회(캐시 저장), 그리고 어드민이 원서를 수정한다면 데이터베이스에서는 원서가 수정된 상태이지만 원서 조회를 진행하였기 때문에 수정 전의 캐시 정보가 남아있어 수정 전의 원서가 조회되게 됩니다.
- 위 문제를 해결하기 위해 원서 생성, 수정시에 기존 원서에 대한 캐시 정보가 있다면 수동으로 캐시 정보를 업데이트 하도록 개선하였습니다.
* EntranceTestResult, ScreeningChangeHistory 테이블의 PK 컬럼명이 잘못되어있어 수정하였습니다.

[oneseo] 원서 관련 redis 캐시 문제 개선

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/EntranceTestResult.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/Oneseo.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/DownloadExcelService.java
src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/DownloadExcelServiceTest.java

Oneseo 테이블의 변경된 테이블 컬럼 스펙에 따라 엔티티 필드를 수정하였습니다.
`entrance_intention_yn` column 추가, `decide_major` column 위치변경 (tb_entrance_test_result -> tb_oneseo)

[oneseo] 원서 관련 변경된 테이블 컬럼 스펙에 맞춰 엔티티 필드 수정

---

src/main/java/team/themoment/hellogsmv3/global/common/converter/IntegerListConverter.java

MiddleSchoolAchievement의 중학교 성적 데이터를 저장하는 컬럼의 Convert 메서드의 null check를 추가하였습니다.
DML로 직접 DB에 데이터를 insert 할때 중학교 성적 column에 NULL을 할당한다면 JPA 단에서 NULL 값을 Integer List로 변환하려하기 때문에 NPE가 발생합니다.
원서 생성 API를 사용해 원서를 저장한다면 DB 저장시 컨버트 메서드를 통해 Null값을 String으로 변환해 저장하기 때문에 NPE가 발생하지 않았습니다.
위의 상황을 고려하여 String to Integer List 변환 메서드에 null check를 추가하였습니다.

[oneseo] MiddleSchoolAchievement 컨버트 메서드 null check 추가

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/custom/impl/CustomOneseoRepositoryImpl.java

수험표 출력시 비정상적으로 많은 양의 데이터가 반환되는 문제를 해결하였습니다.
> 실제 원서 개수는 20개지만 400개의 rows가 출력되는 것을 볼 수 있다...
기존 수험표 출력 쿼리입니다. from 절에 `tb_oneseo`, `tb_oneseo_privacy_detail` 테이블이 지정되어있지만, `tb_oneseo_privacy_detail` 테이블에 대한 조인 문은 존재하지 않습니다.
그렇기 때문에 `tb_oneseo_privacy_detail` 테이블에 대함 검색 결과에 카테시안 곱 현상이 발생하여 문제가 발생한 것으로 보입니다.
문제파악 후  `tb_oneseo_privacy_detail` 테이블에 대한 조인 절을 포함시켜 문제를 해결하였습니다.

[oneseo] 수험표 출력 join 쿼리 문제 수정

---

src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java

배포 환경(stage)에서 PATCH 메서드의 API에서 500에러가 발생하는것을 확인하였습니다.
cors 설정에서 PATCH method에 대한 allow를 추가하지 않아 발생하는 문제였으므로 누락되어있던 PATCH method allow를 추가하였습니다.

[global] 누락 된 cors 허용 메서드 PATCH 추가

---

src/main/java/team/themoment/hellogsmv3/global/security/handler/CustomUrlAuthenticationSuccessHandler.java

#124 해당 PR에서 수정한 X_HG_ENV enum class 이름을 수정하지 않은 부분이 있어 ci 도중 컴파일 오류가 발생하여 수정하였습니다.

[global] X_HG_ENV header name 변경

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/custom/impl/CustomOneseoRepositoryImpl.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyRealOneseoArrivedYnService.java
src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoServiceTest.java
src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyRealOneseoArrivedYnServiceTest.java
src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/SearchOneseoServiceTest.java

원서 관련 서비스 로직에서 희망전형을 적용전형으로 변경하였습니다.
- #134 해당 PR에서 원서 엑셀 출력의 변경사항을 테스트코드에 반영하지 않아 수정하였습니다.
- `appliedScreening - 적용전형`은 1차 배치 이후에 값이 들어가기 때문에 **수험표 출력 기능은 appliedScreening을 사용하고, 나머지 기능들은 wanatedScreening을 사용하도록 변경**하였습니다.

[oneseo] 원서 엑셀 출력 및 원서 관련 서비스 희망전형 적용 전형으로 변경

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoService.java
src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java
src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoServiceTest.java

1차 전형 결과 산출 이후에는 원서 수정이 막히도록 변경하였습니다.
- `TimeBsaesFilter`에 (원서 작성 기간에만 요청이 가능하도록) 원서 수정 API를 추가하였습니다.
- 원서 수정 service 로직에 `firstTestPassYn` 필드를 기준으로 1차 전형 결과 산출 이후인지 확인하여 validation 하는 메서드를 추가하였습니다.

[oneseo] 1차 전형 결과 산출 이후에 원서 수정 막도록 변경

---

src/main/java/team/themoment/hellogsmv3/domain/member/controller/MemberController.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/controller/OneseoController.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/EntranceIntentionReqDto.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/response/SearchOneseoResDto.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/Oneseo.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/custom/impl/CustomOneseoRepositoryImpl.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyEntranceIntentionService.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoService.java

입학등록 동의서 제출 여부 수정 기능을 추가하였습니다.
- `/entrance-intention/{memberId}` 입학등록 동의서 제출 여부를 수정할 수 있습니다.
- 최종 합격한 지원자의 원서만 수정이 가능합니다. (최종 합격자에게 할당되는 `decidedMajor` 필드로 여부 판단)
- 원서 검색 dto에 `entranceIntentionYn` 필드를 추가하였습니다.
* 인증번호 관련 컨트롤러 메서드 파라미터에 `@Valid` 어노테이션이 누락되어있어 추가하였습니다.

[oneseo] 입학등록 동의서 제출 여부 수정 기능 추가

---

src/main/java/team/themoment/hellogsmv3/global/thirdParty/aws/s3/controller/S3Controller.java
src/main/java/team/themoment/hellogsmv3/global/thirdParty/aws/s3/dto/response/UploadImageResDto.java

이미지 업로드 API의 response 스펙이 API 문서 스펙과 맞지 않아 수정하였습니다.
> 수정 전
> 수정 후

[global] 이미지 업로드 API response 스펙에 맞도록 수정

---

build.gradle
src/main/resources/application.yml
src/main/resources/logback-spring.xml

stage 환경에서 cloud watch 로그그룹에 application 로그를 적재하고 모니터링할 수 있는 시스템을 구축하였습니다.
logback-spring.xml의 파일은 아래의 내용을 담고있습니다.
- 기본 profile일 시 콘솔에 로그를 출력합니다.
- stage profile일 시 `hellogsm-stage-log` 로그그룹에 로그스트림을 생성하고 applicaiton 로그를 적재합니다.
- 10초에 한번씩 로그를 cloud watch로 전송하고, 50개의 로그가 쌓여도 전송합니다.
* 기존 s3, sns 서비스를 사용할때 사용한 iam에 `CloudWatchLogsFullAccess` 권한을 등록하였고, 인스턴스 내부에 aws-cli로 iam의 accessKey, seacretKey를 등록하여 iam 권한을 적용시켰습니다.

[global] stage 환경 cloud watch 로그 수집 시스템 구축

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/controller/OneseoController.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/OneseoTempReqDto.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/OneseoTempStorageService.java

원서 임시저장시 request body의 모든 필드가 nullable 해야하기 때문에 원서 임시저장 용 dto 객체를 추가하여 적용하였습니다.

[oneseo] 원서 임시저장시 null일 수 있는 필드 처리용 dto 추가

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoService.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyRealOneseoArrivedYnService.java

실물 원서 제출을 위해 원서 출력시 접수번호가 필요하기 때문에 접수번호 할당 시점을 원서 생성 시점으로 변경하였습니다.

[onseo] 원서 생성시 접수번호 할당 되도록 변경

---

src/main/java/team/themoment/hellogsmv3/domain/member/controller/MemberController.java
src/main/java/team/themoment/hellogsmv3/domain/member/dto/response/FoundMemberTestRequestResDto.java
src/main/java/team/themoment/hellogsmv3/domain/member/dto/response/FoundMemberTestResDto.java
src/main/java/team/themoment/hellogsmv3/domain/member/service/QueryTestResultService.java
src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java

전형 결과 조회 API를 추가하였습니다.
- `/member/v3/test-result` 해당 지원자의 1차 전형, 2차 전형의 결과를 조회합니다.
- 지원자의 전형 결과를 조회하는 것이기 때문에 해당 로직을 member 도메인 패키지에 두었습니다.

[member] 전형 결과 조회 기능 추가

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/response/MiddleSchoolAchievementResDto.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoService.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoService.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/OneseoService.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/OneseoTempStorageService.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/QueryOneseoByIdService.java
src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/OneseoServiceTest.java

- `FoundOneseoResDto` 객체 필드에 환산일수 필드를 추가하였습니다.
- 원서 생성, 수정, 임시저장, 내 원서 조회시 환신일수를 계산하므로 원서 공통 서비스에 환산일수 계산 로직을 작성하였습니다.
- 원서 공통 서비스의 환산일수 계산 로직에 대해 테스트코드를 작성하였습니다.

[oneseo] 환산일수 계산 기능 추가

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/OneseoReqDto.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoService.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoService.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/OneseoService.java

졸업자, 검정고시 지원자는 중학교 관련 정보들을 받지 않도록 변경하였습니다.
- 졸업자, 검정고시 지원자는 중학교 이름, 중학교 위치, 담임선생님 성함, 담임선생님 전화번호 정보를 원서 생성, 수정시 받지 않도록 변경하였습니다. (nullable)
- 변경에 추가로 중학교 졸업예정인 지원자는 위의 정보를 입력하지 않았을때 원서 생성, 수정을 막는 validation 메서드를 만들었습니다.

[oneseo] 졸업자, 검정고시 지원자는 중학교 관련 정보를 받지 않도록 변경

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/controller/OneseoController.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/response/CalculatedScoreResDto.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/response/FoundOneseoResDto.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateGedService.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateGradeService.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateMockScoreService.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoService.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoService.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/QueryOneseoByIdService.java

작성한 원서 출력시 지원자의 성적 환산 값들이 필요합니다. 기존에는 해당 값을 fe 단에서 직접 계산하여 사용했는데, 서버 단에서 계산 로직을 가져가는 것이 일관성이 있다고 생각되어 원서 조회 res dto의 스펙에 성적 환산 값을 추가하였습니다.
- 모의성적 계산 res dto의 스펙이 원서 조회시 필요한 스펙과 동일하여 해당 res dto객체의 이름을 공통으로 사용할 수 있게 변경 후 재사용 하였습니다. (MockScoreResDto -> CalculatedScoreResDto)

[oneseo] 원서 조회 dto 스펙에 성적 환산 값 추가

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/response/FoundOneseoResDto.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoService.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoService.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/QueryOneseoByIdService.java

- 원서 조회 res dto의 환산점수 필드의 네이밍을 개선하였습니다. `calculatedScoreResDto` -> `calculatedScore`

[oneseo] 원서 조회 res dto의 환산점수 필드 네이밍 개선

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/response/CalculatedScoreResDto.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/response/GeneralSubjectsScoreDetailResDto.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateGradeService.java

- 지원자의 원서 출력시 개별 교과성적 환산점수가 필요해 원서 조회 res dto의 CalculatedScoreResDto 필드에 개별 교과성적 환산점수 필드를 추가하였습니다.

[oneseo] 원서 조회 dto 스펙에 개별 교과성적 환산점수 추가

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/QueryOneseoByIdService.java

#160 해당 PR에서 반영한 변경 사항에서 원서 조회시 개별 교과성적 환산점수 dto를 주입해주는 부분을 누락하여 수정하였습니다.

[oneseo] 원서 조회시 교과성적 dto 추가되도록 수정

---

src/main/java/team/themoment/hellogsmv3/domain/common/date/controller/DateController.java
src/main/java/team/themoment/hellogsmv3/domain/common/date/dto/DateResDto.java
src/main/java/team/themoment/hellogsmv3/domain/common/date/service/QueryDateService.java
src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java
src/main/java/team/themoment/hellogsmv3/global/security/data/ScheduleEnvironment.java
src/main/resources/application.yml

FE에서 버튼or페이지의 트리거가 되는 date response api 구현하였습니다.
- `GET /date` 요청을 통해 아래 date를 반환해줍니다.
- 원서접수 (시작&끝)
- 1차전형결과발표
- 최종결과발표
- 직무적성평가
- 심층면접
- 기존 원서접수기간을 나타내는 변수 이름을 변경하였습니다. (`ReceptionDate` -> `oneseoSubmission`)
- 기존 패키지에 date를 처리할 적절한 도메인이 없다고 판단하여, common->date 패키지를 생성 후 사용하였습니다.

[global] date response api 구현

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateGradeService.java

성적계산시 자유학기제에 공백을 입력시 요청으로 보낸 모든 학기의 환산값을 더해 교과점수 만점을 초과하는 상황이 발생하여 수정하였습니다.
- fe에서 만약 1-1학기가 자유학기제라면 liberalSystem = 자유학기제, freeSemester를 공백으로 요청하기 때문에 이를 수정하였습니다.
- 추가로 유효하지 않은 학기를 요청할 시 예외를 발생시키도록 validSemester 메서드를 추가하였습니다.

[oneseo] 성적 계산시 자유학기제 학기가 공백일 시 1-1학기로 계산하도록 수정

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateGradeService.java

기존 로직에서는 자유학기제 학기(freeSemester)가 null일시 공백으로 치환하였습니다. (NPE를 방지하기 위해서), 하지만 #163  해당 PR에서 freeSemester가 공백일시 1-1학기로 계산하도록 변경하였습니다.
하지만 이렇게 된다면 freeSemester가 null일때, 즉 자유학년제로 성적 계산시 freeSemester가 null로 들어가지만 공백으로 치환되기 때문에 성적계산이 제대로 동작하지 않는 현상이 발생했습니다.
이 때문에 freeSemester를 null일 시 공백, 공백일 시 1-1로 치환하는 로직을 추가하였습니다.

[oneseo] 성적 환산시 자유학기제 학기 null, 공백 check 추가

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoService.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoService.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/OneseoService.java

원서 수정시에 접수번호(submitCode)를 새로 할당하지 않아서 submitCode 필드가 NULL이 되는 문제가 있어 접수번호 할당 메서드를 oneseo 관련 공통 로직 서비스인 OneseoService로 빼서 원서 생성, 수정시 변경되는 전형에 따라 submitCode를 할당하여 저장하도록 변경하였습니다.

[oneseo] 원서 수정시에도 접수번호가 변경된 전형에 따라 수정되도록 수정

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateGradeService.java

1-1학기가 자유학기제인 졸업예정자의 학기별 환산값 조건식에 누락된 부분을 수정하였습니다.
이해를 돕기 위해 아래 캡쳐를 참고해주시면 좋을것 같습니다.
> 수정전, 1-1학기가 자유학기라면 1-2, 2-1, 2-2 학기가 각각 54, 54, 72점이 만점으로 들어가야하지만 54, 54, 54로 잘못 계산되는 것을 확인할 수 있습니다.
> 수정후, 2-2학기에 누락된 조건식을 추가하여 정상적으로 54, 54, 72로 계산되는것을 확인할 수 있습니다.
<br />
- 자유학기 관련 valid 메서드를 추가하여 비정상적인 상황을 방지하였습니다. 80b3383a0437f7643fcddbfcf9042439049ac68c

[oneseo] 잘못된 1-1 자유학기 관련 성적계산 조건식 수정

---

src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/SearchOneseoServiceTest.java

#171 해당 PR에서 제거된 도메인을 의존하는 테스트코드가 존재하여 수정하였습니다.

[oneseo] 삭제된 도메인의 클래스를 의존하고 있는 import를 변경

---

src/main/java/team/themoment/hellogsmv3/domain/member/dto/response/FoundMemberTestResDto.java
src/main/java/team/themoment/hellogsmv3/domain/member/service/QueryTestResultService.java

최종결과 발표 시 배정학과를 표시하기 위해 전형 결과 조회 api response 필드에 배정학과를 추가하였습니다.

[member] 전형 결과 조회 api 스펙에 배정 학과 추가

---

src/main/java/team/themoment/hellogsmv3/global/common/converter/StringListConverter.java

`tb_middle_school_achievement` 테이블의 컬럼과 엔티티의 매핑에 사용되는 컨버터에 null-check 처리가 되어있지 않아 null 값이 할당되어있는 검정고시 원서에서 NPE가 발생하여 null-check를 추가하였습니다.

[oneseo] String list 컨버터 null check 추가

---

src/main/java/team/themoment/hellogsmv3/domain/member/dto/response/FoundDuplicateMemberResDto.java
src/test/java/team/themoment/hellogsmv3/domain/member/service/QueryCheckDuplicateMemberServiceTest.java

기존 파스칼케이스로 작성되었던 중복회원확인 API res dto 필드명을 스네이크케이스로 변경하였습니다.

[member] 중복 확인 API res dto 필드 스네이크 케이스로 변경

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/response/ArtsPhysicalSubjectsScoreDetailResDto.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/response/CalculatedScoreResDto.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateGradeService.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/QueryOneseoByIdService.java
src/main/resources/application.yml

**졸업예정자**의 원서 조회시 개별 학기별 예체능 환산점 계산식을 추가하였습니다.
개별 학기별 예체능 환산점의 배점 계산식은 아래와 같습니다.
```
60 * (해당 학기의 성적이 있는 예체능 교과 수 / 성적이 있는 총 예체능 교과 수)
```
해당 배점 식으로 각 학기별 예체능 환산점을 구할 수 있습니다.
위와 같이 `FoundOneseoResDto` dto 필드에 `artsPhysicalSubjectsScoreDetail` 필드를 추가하여 학기별 예체능 환산점을 반환합니다.

[oneseo] 개별 학기별 예체능 환산점 계산식 추가

---

src/main/java/team/themoment/hellogsmv3/domain/member/entity/AuthenticationCode.java

인증번호 redis-hash의 TTL을 3분으로 수정하였습니다.

fix(member): 인증번호 유효기간 TTl 3분으로 수정

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/response/ArtsPhysicalSubjectsScoreDetailResDto.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateGradeService.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoService.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/QueryOneseoByIdService.java

성적확인서를 졸업자도 출력해야한다는 요구사항이 생겨 예체능 개별학기 환산 필드에 3-2 학기를 추가하였습니다.
기존 로직에 3-2 학기 필드를 추가하여 졸업 상태가 졸업자(GRADUATE)인 지원자라면 3-2 학기 환산점을 계산하도록 하였습니다.

[oneseo] 예체능 개별학기 환산점 3-2 학기 필드 추가 (졸업자)

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyAptitudeEvaluationScoreService.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyInterviewScoreService.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoService.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyRealOneseoArrivedYnService.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/OneseoService.java
src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyAptitudeEvaluationScoreServiceTest.java
src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyInterviewScoreServiceTest.java
src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyRealOneseoArrivedYnServiceTest.java

특정 시험 이후에는 동작하지 않아야하는 작업에 대한 처리와 평가 점수 입력 범위에 대한 검증 로직을 추가하였습니다.
- 특정 시점 이후에는 동작하지 않아야 하는 작업에 대한 validate를 추가하였습니다. (1차 평가 이후 불가능: 서류제출여부 수정, 2차 평가 이후 불가능: 평가점수 수정)
- 평가 점수 입력 범위에 대한 검증 메서드를 추가하였습니다. (인적성, 면접 점수 0점 ~ 100점 범위 제한)

[oneseo] 특정 시점 이후에는 동작하지 않아야 하는 작업 수정 및 평가 점수 검증 메서드 추가

---

src/main/java/team/themoment/hellogsmv3/domain/member/service/CreateMemberService.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateGradeService.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/DownloadExcelService.java
src/main/resources/application.yml
src/test/java/team/themoment/hellogsmv3/domain/member/service/CreateMemberServiceTest.java

fdfcbde24f27a50e940ae1f50e662362ddbcc36e
- 예체능 점수 모두 없음(0)으로 입력시 개별학기 환산점 계산로직에서 `0 / 0` 계산이 발생(500에러)하는 문제 해결
fe202193fd56ce859bc57ac90bdedc14e0e92469
- 원서 출력시 평가점수(인적성, 면접)가 null이라면 환산총점을 계산하지 않도록 수정
57260559698627c9d140f5836b6cbc3e59d49a3d
- 비교과 점수(출결, 봉사점수) 음수 입력 validate 메서드 추가
fb37df6e6bef83beb3edc013db4b1f90daa1c427
- 접수기간 이후에는 회원정보 삭제되지 않도록 더 안전하게 조건식을 추가하였습니다.
2a96853d1284c8d464779740f74b64a95ba8d8da
- 성적 계산식에서 validate 하는 로직을 메서드로 분리하여 개선하였습니다.

[onesoe] 테스트 중 발생한 원서 관련 트러블 슈팅

---

build.gradle
src/main/java/team/themoment/hellogsmv3/HelloGsmV3Application.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/event/OneseoApplyEvent.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/event/handler/OneseoApplyEventHandler.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoService.java
src/main/java/team/themoment/hellogsmv3/global/security/data/HeaderConstant.java
src/main/java/team/themoment/hellogsmv3/global/security/handler/CustomUrlAuthenticationSuccessHandler.java
src/main/java/team/themoment/hellogsmv3/global/thirdParty/feign/client/DiscordAlarmClient.java
src/main/java/team/themoment/hellogsmv3/global/thirdParty/feign/client/dto/request/DiscordAlarmReqDto.java
src/main/java/team/themoment/hellogsmv3/global/thirdParty/feign/client/type/Env.java
src/main/java/team/themoment/hellogsmv3/global/thirdParty/feign/client/type/NoticeLevel.java
src/main/java/team/themoment/hellogsmv3/global/thirdParty/feign/config/FeignConfig.java
src/main/java/team/themoment/hellogsmv3/global/thirdParty/feign/config/FeignErrorDecoder.java
src/main/java/team/themoment/hellogsmv3/global/thirdParty/feign/service/DiscordAlarmFeignClientService.java
src/main/resources/application.yml

원서 작성시 디스코드 알림을 전송하는 기능을 추가하였습니다.
open feign client를 사용해서 디스코드 relay server API로 알림을 전송하도록 구현하였습니다.
원서 생성 서비스 클래스 원서 생성 이벤트 publish -> 원서 생성 이벤트 핸들러(원서 생성 커밋 후 실행)에서 비동기로 feign client 호출 -> 디스코드 알림 전송

[oneseo] 원서 작성시 디스코드 알림 전송 기능 추가

---

build.gradle
src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoServiceTest.java

- #192 해당 PR 변경사항에 대한 테스트코드를 수정하였습니다.
- 불변객체(record)는 mockito에서 기본적으로 모킹할 수 없어 mockito-inlin 라이브러리를 추가하였습니다.

[oneseo] 원서 생성 테스트코드 수정 및 불변객체 모킹 라이브러리 추가

---

DockerfileProd

prod docker file 컨테이너 실행시 system time 서울 시간대로 설정하는 커멘드를 추가하였습니다.

[global] prod docker file에 system time 서울 시간대로 설정하는 커멘드 추가

---

src/main/java/team/themoment/hellogsmv3/domain/member/entity/Member.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/Oneseo.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoService.java

원서 생성 로직 트랜잭션의 고립도를 4단계(SERIALIZABLE)로 설정하여 동시성 문제가 발생하지 못하도록 막았습니다.
- 원서 생성은 자주 발생하는 작업이 아니기 때문에 데드락이 발생할 수 있어도 안정성을 위해 고수준의 고립도를 설정하여 동시성 문제를 방지하였습니다.
- 원서 엔티티에 1:N 매핑 관계인 필드의 기본값을 설정하기 위해 @Builder.Default 어노테이션을 설정하였습니다.
- 지원자의 email은 겹칠 수 있기 때문에 JPA 매핑 설정 정보에서 유니크 조건을 제거하였습니다.

[oneseo] 원서 생성 트랜잭션 고립도 SERIALIZABLE로 설정하여 동시성 문제 방지

---

build.gradle
src/main/java/team/themoment/hellogsmv3/HelloGsmV3Application.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoService.java

원서 생성 트랜잭션의 고립도는 SERIALIZABLE로 가장 고수준으로 설정되어있습니다. 그렇기 때문에 동일한 트랜잭션 작업시 데드락이 발생할 수 있어 스프링 retry 라이브러리를 사용해서 데드락 발생시 트랜잭션을 재시도 하게 개선하였습니다.
> 재시도 기능 추가 전, 원서 생성을 빠르게 두번 했다면 데드락이 발생하여 한쪽에서 500에러 발생
> 재시도 기능 추가 후, 원서 생성을 빠르게 두번 해서 데드락 발생시 한쪽 트랜잭션이 1000ms를 기다리고 최대 2번 재시도를 진행해서 정상적으로 원서 생성 후 중복 원서 예외 발생

[oneseo] 원서 생성 로직 실행중 데드락 발생시 retry 어노테이션 추가

---

src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java

원서 조회 API에 접수 기간에만 요청 가능하게 제한하는 필터가 걸려있어 제거하였습니다.

[oneseo] 원서 조회 API 기간 필터 제외

---

src/main/java/team/themoment/hellogsmv3/domain/common/testResult/controller/TestResultController.java
src/main/java/team/themoment/hellogsmv3/domain/common/testResult/dto/request/FoundTestResultReqDto.java
src/main/java/team/themoment/hellogsmv3/domain/common/testResult/dto/response/FoundTestResultResDto.java
src/main/java/team/themoment/hellogsmv3/domain/common/testResult/service/QueryTestResultService.java
src/main/java/team/themoment/hellogsmv3/domain/common/testResult/service/impl/GenerateTestResultCodeServiceImpl.java
src/main/java/team/themoment/hellogsmv3/domain/common/testResult/type/TestType.java
src/main/java/team/themoment/hellogsmv3/domain/member/controller/MemberController.java
src/main/java/team/themoment/hellogsmv3/domain/member/dto/request/AuthenticateCodeReqDto.java
src/main/java/team/themoment/hellogsmv3/domain/member/entity/AuthenticationCode.java
src/main/java/team/themoment/hellogsmv3/domain/member/entity/type/AuthCodeType.java
src/main/java/team/themoment/hellogsmv3/domain/member/repo/CodeRepository.java
src/main/java/team/themoment/hellogsmv3/domain/member/service/AuthenticateCodeService.java
src/main/java/team/themoment/hellogsmv3/domain/member/service/CommonCodeService.java
src/main/java/team/themoment/hellogsmv3/domain/member/service/CreateMemberService.java
src/main/java/team/themoment/hellogsmv3/domain/member/service/GenerateCodeService.java
src/main/java/team/themoment/hellogsmv3/domain/member/service/QueryMyFirstTestResultService.java
src/main/java/team/themoment/hellogsmv3/domain/member/service/QueryMySecondTestResultService.java
src/main/java/team/themoment/hellogsmv3/domain/member/service/impl/GenerateCodeServiceImpl.java
src/main/java/team/themoment/hellogsmv3/domain/member/service/impl/GenerateTestCodeServiceImpl.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/custom/CustomOneseoRepository.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/custom/impl/CustomOneseoRepositoryImpl.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/OneseoService.java
src/main/java/team/themoment/hellogsmv3/global/config/SwaggerConfig.java
src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java
src/main/resources/application.yml
src/test/java/team/themoment/hellogsmv3/domain/member/service/AuthenticateCodeServiceTest.java
src/test/java/team/themoment/hellogsmv3/domain/member/service/CommonCodeServiceTest.java
src/test/java/team/themoment/hellogsmv3/domain/member/service/CreateMemberServiceTest.java
src/test/java/team/themoment/hellogsmv3/domain/member/service/impl/GenerateCodeServiceImplTest.java
src/test/java/team/themoment/hellogsmv3/domain/member/service/impl/GenerateTestCodeServiceImplTest.java

지원자가 직접 로그인하여 모달을 통해 결과를 확인하는 것이 아닌 부모님이나 선생님이 지원자 학생의 결과를 조회할 수 있는 기능을 추가하였습니다.
결과 조회는 조회하려는 원서에 작성된 부모님 or 선생님의 전화번호와 (**1차 전형: 접수번호, 2차전형: 수험번호**)의 조합으로 조회가 가능합니다.
회원가입시 사용되는 인증코드 redis hash에 `testType` 인덱스 필드를 추가하여 회원가입용 코드, 결과확인용 코드로 구분하였습니다.
인증코드 인증 후에 결과 확인 기간이 지났는지, 전화번호, 접수번호 or 수험번호의 조합인 원서가 존재하는지 확인 후 결과를 반환합니다.
구조 변경과 테스트코드 수정으로 인해 file changes가 많아졌습니다. 리뷰어 분들께 죄송합니다.
AuthenticationCode의 변경된 구조와 common.testResult 부분의 로직을 중심적으로 확인해주시면 감사하겠습니다.

[test-result] 결과 조회 기능 추가

---

src/main/java/team/themoment/hellogsmv3/HelloGsmV3Application.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/event/handler/OneseoApplyEventHandler.java
src/main/java/team/themoment/hellogsmv3/global/config/AsyncConfig.java
src/main/java/team/themoment/hellogsmv3/global/exception/GlobalAsyncExceptionHandler.java

기존 디스코드 알람 전송 비동기 처리는 따로 스레드풀 설정이 없어 SimpleAsyncTaskExecutor가 사용되었습니다.
이는 스레드를 관리하는 게 아니라 매번 새로 만들기 때문에 낭비로 이어질 수 있습니다. 
이를 방지하기 위해 ThreadPoolTaskExecutor를 사용해 스레드풀을 정의하였습니다.
corePoolSize=1, queueCapacity=unlimit, maxPoolSize=unlimit으로 설정하였습니다.
큐 용량에 제한을 두어 스레드를 늘리는게 오히려 성능 저하가 오는 테스트 자료를 보았습니다. (생성 리소스가 메모리에 대기시켜두는 거보다 느림)
또한 corePoolSize도 [자바 전문가가 제시하는 공식](https://blog.devops.dev/how-to-determine-java-thread-pool-size-a-comprehensive-guide-4f73a4758273)을 적용하여 1이 적당할 것이라고 판단하였습니다.
비동기 메서드에서 발생하는 예외를 처리하기 위해 AsyncUncaughtExceptionHandler를 구현하였습니다.
로그 내용은 발생 method와 exception 트레이스로 하였습니다.
궁금한점 혹은 이견 있으시면 편하게 말씀해주세요

[oneseo] 디스코드 알람 비동기 처리 스레드풀 정의

---

build.gradle
src/main/java/team/themoment/hellogsmv3/HelloGsmV3Application.java
src/main/java/team/themoment/hellogsmv3/domain/member/repo/MemberRepository.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoService.java

기존
- valid자원에는 s lock, 쓰기 자원에 대해서만 x lock을 걸어 insert에서 lock을 얻지 못하도록 함.
- 불필요한 쿼리가 그대로 나간다는 점에서 이상적이지 않다고 생각하였습니다.
개선
- valid자원에 for update구문을 통한 x lock을 걸어 처음 락을 획득한 스레드가 작업을 마치기 전까지 다른 스레드는 대기하도록 함.
- 최소한의 쿼리만으로 동시성 제어.

[oneseo] 원서 작성 동시성 제어 방식 변경

---

src/main/java/team/themoment/hellogsmv3/domain/member/repo/MemberRepository.java
src/main/java/team/themoment/hellogsmv3/domain/member/service/MemberService.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoService.java

findById 메서드의 불필요한 Lock 제거를 위해 쿼리를 분리하였습니다.
락을 적용할 메서드에 JPQL을 사용해 쿼리를 정의하고 ForUpdate라는 접미사를 붙여주었습니다.
쿼리 - `SELECT m FROM Member m WHERE m.id = :memberId`

[member] findById 쿼리 분리

---

.github/workflows/hellogsm-prod-ci.yml
.github/workflows/hellogsm-stage-ci.yml

- 기존에 CI script에 `gradlew assemble`을 사용하였습니다만, 이는 컴파일만 하고 테스트는 포함되지 않았습니다. 
- `assemble`+ `test` + 부가작업 이 포함된 `build`명령어로 수정하였습니다.

[CI] ci script gradle 명령어 수정

---

src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoServiceTest.java

동시성 제어를 위해 `findByIdForUpdate`를 정의하였는데, 테스트코드에서 수정이 안되어 있어 수정하였습니다.

[oneseo] createOneseoTest member조회 오류 수정

---

.github/workflows/hellogsm-prod-cd.yml

cd script에서 중복으로 실행하던 코드를 삭제했습니다.
hellogsm-prod-cd.yml에서 gradlew에 중복으로 실행권한을 부여하던 부분을 삭제했습니다.
Before
```yml
- name : Setup Gradle's permission
run : chmod +x gradlew
- name: Make yml file
run: touch ./src/main/resources/application-prod.yml
echo "${{ secrets.PROD_WEB_YML }}" > ./src/main/resources/application-prod.yml
shell: bash
- name: Grant execute permission for gradlew
run: chmod +x gradlew
```
After
```yml
- name : Setup Gradle's permission
run : chmod +x gradlew
- name: Make yml file
run: touch ./src/main/resources/application-prod.yml
echo "${{ secrets.PROD_WEB_YML }}" > ./src/main/resources/application-prod.yml
shell: bash
```

fix: gradlew 실행권한 중복부여 코드 삭제

---

scripts/dev-deploy.sh
scripts/prod-deploy.sh

컨테이너가 실행중이지 않을경우 발생하던 CI/CD 잠재적인 에러를 방지했습니다.
docker ps는 실행중인 컨테이너만 반환하므로, 이전버전의 컨테이너가 실행중이지 않다면 걸러낼 수 없었습니다. 그 상태로 `%CONTAINER_NAME을 사용하여 같은 이름의 컨테이너를 docker run을 통해 만드려고 할 경우, 에러가 발생하게 됩니다. 따라서 -a 파라미터로 실행중이지 않은 컨테이너까지 검색하도록 하였습니다.
dev-deploy의 경우 컨테이너가 존재한다면  [(중지 or 무시) -> 삭제]
prod-deploy의 경우 [실행중인 컨테이너 중지 -> 존재하는 컨테이너 삭제]
하도록 변경되었습니다.
prod-deploy도 dev-deploy처럼 짧게 만들수 있었는데, `docker stop $CONTAINER_NAME || true`가 발생하는 에러를 무시하기 때문에 문제가 생길수도 있다고 생각해서 if문 두개로 처리하도록 하였는데 코드가 좀 더러워 보여서 피드백 가능한 부분이 있다면 받고싶습니다.
그런데 또 if문 없이 그냥 이렇게 하시는분들도 있긴하더라구요..
```shell
docker stop $CONTAINER_NAME || true
docker rm$CONTAINER_NAME || true
```
백엔드 과제 하던중 실제로 겪어본 문제입니다.. ㅜㅜ

[ci/cd] 컨테이너가 실행중이지 않을경우 발생하던 CI/CD 에러 해결

---

src/main/java/team/themoment/hellogsmv3/domain/member/service/QueryMyFirstTestResultService.java
src/test/java/team/themoment/hellogsmv3/domain/member/service/QueryMyFirstTestResultServiceTest.java
src/test/java/team/themoment/hellogsmv3/domain/member/service/QueryMySecondTestResultServiceTest.java

내 1차, 2차 테스트 결과 조회 서비스에 테스트 코드를 추가하였습니다.
1차 테스트 결과가 발표되었을 경우 1차 테스트 결과를 반환한다.
1차 테스트 결과가 발표되지 않았을 경우 null을 반환한다(204 no content)
2차 테스트 결과가 발표되었을 경우 2차 테스트 결과와 배정된 학과를 반환한다.
2차 테스트 결과가 발표되지 않았을 경우 null을 반환한다(204 no content)
서비스 로직이 동일하여 하나의 브랜치에서 두 서비스를 동시에 작업했습니다.

[member] QueryMyFirstTestResultService, QueryMySecondTestResultService 테스트 코드 추가

---

src/main/java/team/themoment/hellogsmv3/domain/common/testResult/service/QueryFirstTestResultByNameAndBirthAndPhoneNumberService.java
src/test/java/team/themoment/hellogsmv3/domain/common/service/QueryFirstTestResultByNameAndBirthAndPhoneNumberServiceTest.java
src/test/java/team/themoment/hellogsmv3/domain/common/service/QuerySecondTestResultByNameAndBirthAndPhoneNumberServiceTest.java

QueryFirstTestResultByNameAndBirthAndPhoneNumberService, 
QuerySecondTestResultByNameAndBirthAndPhoneNumberService에 테스트 코드를 추가하였습니다.
QueryFirstTestResultByNameAndBirthAndPhoneNumberService 클래스의 -> execute 메소드는 -> 
1차 전형 결과 발표 전이라면 -> 예외를 던진다.
생년월일 형식이 잘못되었다면 -> 예외를 던진다.
주어진 정보를 가진 원서를 찾을 수 없다면 -> 예외를 던진다.
주어진 정보를 가진 원서를 찾을 수 있다면 -> 1차 전형 결과를 반환한다.
QuerySecondTestResultByNameAndBirthAndPhoneNumberService 클래스의 -> execute 메소드는 -> 
2차 전형 결과 발표 전이라면 -> 예외를 던진다.
생년월일 형식이 잘못되었다면 -> 예외를 던진다.
주어진 정보를 가진 원서를 찾을 수 없다면 -> 예외를 던진다.
주어진 정보를 가진 원서를 찾을 수 있다면 -> 2차 전형 결과와 배정 학과를 반환한다.

[common] QueryFirstTestResultByNameAndBirthAndPhoneNumberService, QuerySecondTestResultByNameAndBirthAndPhoneNumberService에 테스트 코드 추가

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/controller/OneseoController.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/internal/SecondTestResultDto.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/custom/CustomOneseoRepository.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/custom/impl/CustomOneseoRepositoryImpl.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/UploadExcelService.java
src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java

2차 전형 점수를 엑셀 파일로 업로드 할 수 있도록 하였습니다.
1번째 열은 수험번호
2번째 열은 역검점수
3번째 열은 면접점수를 나타냅니다.
첫번째 행은 헤더 행으로 간주하여 읽지 않습니다.
점수를 BigDecimal 형태로 읽고 각 응시자별로 점수를 저장합니다.
Excel은 기본적으로 숫자 행을 double 형태로 저장하여 추후에 부동소수점으로 인한 손실을 고려하여
문자열 행으로 입력 받도록 구현하였습니다.
현재 코드상으로 엑셀에 입력된 각 행별로 jpa 쿼리가 실행됩니다.
비효율적임을 인지했으나 각각의 다른 데이터를 입력하는데에 있어서 querydsl과 jpa만으로 힘들다고 생각하였고,
다른 방법을 사용해서 구현하더라도 매우 긴 쿼리와 ORM 미사용이 단점이 될 수 있다고 우려했습니다.
결과적으로 어드민이 매우 적은 횟수로 사용하게될 api이고 하고, 위와 같은 이유로 여러번의 쿼리를 날리는 형태로 구현하게 되었습니다.
이에 대해 적절한 해결책이나 피드백이 있다면 해주시면 좋겠습니다!
점수를 입력할 때 숫자 행이 아닌 문자열 행으로 입력해야 합니다.
서식에서 행 타입을 텍스트로 지정할 수 있습니다.

[oneseo] 2차전형 엑셀 점수 업로드 api

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateGedService.java

FE에서 필요한 필드를 보내지 않았을때 NPE가 발생하던 문제에 대해, null 검사후 예외를 던지도록 해결하였습니다.
gedAvgScore가 입학 전형에 따라, nullable이 바뀌는 필드이기 때문에 @NotNull validator를 사용하기에는 무리가 있었습니다.
추후에 다른 Dto를 포함하여, Dto 클래스를 위한 각각의 validator를 구현하는것으로 개선할 수 있을것 같습니다.

[oneseo] CalculateGedScoreService에서 발생하던 npe 예외처리 추가

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/EntranceTestFactorsDetail.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/EntranceTestResult.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/MiddleSchoolAchievement.java

입학요강과 상이했던 소수점자리 계산을 일치하도록 변경했습니다.
입항요강상 환산 점수는 소수점 넷째 자리에서 반올림해서, 소수점 세자리까지 나타내야합니다.
하지만 Hibernate에서 mysql에 BigDecimal을 나타내기 위해 기본적으로 Number(38,2) 타입을 사용하여, 소수점 둘째 자리까지만 저장됩니다.
이번 변경에서는 소수점 셋째 자리까지 저장해야하는 필드들의 scale을 3으로 변경하고, 일부 둘째 자리까지 저장하도록 하는 필드도 scale을 2로 명시하도록 변경하였습니다.
Merge할때 db column을 변경된 코드에 맞게 변경해야합니다.

[oneseo] 입학요강과 상이했던 점수 소수점 자리 반영

---

scripts/dev-deploy.sh

개발 환경에 배포 시 인스턴스에 과거 버전의 이미지,컨테이너가 삭제되지 않고 누적되어 쌓여가는 문제가 있었습니다.이를 배포 시 해결하는 명령어를 스크립트에 추가하였습니다
개발 환경에 배포 시 인스턴스에 과거 버전의 이미지,컨테이너가 삭제되지 않고 누적되어 쌓여가는 문제가 있었습니다.
이로 인하여 지속적으로 
경보 상태에 들어가 알림이 반복되며 개발자가 직접 인스턴스에 접속하여 Docker 정리 명령어를 입력하여 저장공간을 확보해주어야 하였습니다.
급기야 
```
[stderr]#7 ERROR: failed to copy files: userspace copy failed: write /var/lib/docker/overlay2/fgixhxuky412g7sn1zkdph94o/merged/hellogsm-server-v3/hellogsm-stage-server.jar: no space left on device
...
[stderr]ERROR: failed to solve: failed to copy files: userspace copy failed: write /var/lib/docker/overlay2/fgixhxuky412g7sn1zkdph94o/merged/hellogsm-server-v3/hellogsm-stage-server.jar: no space left on device
[stderr]docker: Error response from daemon: mkdir /var/lib/docker/overlay2/ba22b3b8f2ad9e4469e7f0d94adde8f1e93e781ab82fe3f68de2 …
```

[ci/cd] 개발 환경 배포 시 저장공간 확보를 위한 명령어 추가

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/EntranceTestFactorsDetail.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/EntranceTestResult.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/MiddleSchoolAchievement.java

점수를 나타내는 필드들의 소수점과 정확도를 알맞게 명시하였습니다.
- #256 PR에서 jpa에서 scale만 명시할시 precision과 scale 모두 기본값이 들어가는 문제가 있어, precision을 명시하였습니다.
- 역량검사 점수가 정수형, 100점 만점 형식의 자료형으로 확인되어서 scale 부분을 삭제하였습니다.
추후에 정수형으로 바꾸는것도 고려할 수 있을것 같습니다.

[oneseo] BigDecimal JPA Column 소수점, 정확도 명시

---

src/main/java/team/themoment/hellogsmv3/domain/common/utility/controller/UtilityController.java
src/main/java/team/themoment/hellogsmv3/domain/common/utility/service/DeleteMemberService.java
src/main/java/team/themoment/hellogsmv3/domain/common/utility/service/DeleteOneseoService.java
src/main/java/team/themoment/hellogsmv3/domain/member/repository/CodeRepository.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/OneseoRepository.java
src/main/java/team/themoment/hellogsmv3/global/config/SwaggerConfig.java
src/test/java/team/themoment/hellogsmv3/domain/common/operation/service/AnnounceFirstTestResultServiceTest.java
src/test/java/team/themoment/hellogsmv3/domain/common/operation/service/AnnounceSecondTestResultServiceTest.java
src/test/java/team/themoment/hellogsmv3/domain/common/operation/service/QueryAnnounceTestResultServiceTest.java
src/test/java/team/themoment/hellogsmv3/domain/common/utility/service/DeleteMemberServiceTest.java
src/test/java/team/themoment/hellogsmv3/domain/common/utility/service/DeleteOneseoServiceTest.java

개발 상황에서 팀원들이 필요할 때 원서와 계정을 삭제할 수 있도록 API 2종을 구현하고 테스트 코드를 작성하였습니다
원서 삭제 API와 회원 탈퇴 API를 구현하였습니다.
`common/utility` 패키지를 생성하여 구현하였으며 새로운 도메인으로 `utility`를 추가하였습니다.
원서 삭제 시 원서와 더불어 Redis에 캐싱된 정보까지 삭제하도록 하였으며 회원 탈퇴시에는 작성된 원서와 저장된 인증용 코드까지 삭제하도록 하였습니다.해당 API들의 비즈니스 로직을 검증하는 테스트 코드까지 작성하였습니다.
해당 엔드포인트는 프로파일이 `prod` 라면 Bean으로 등록되지 않아 동작하지 않습니다.
부가적으로 기존에 존재하던 `common.operation`의 하위 서비스 클래스들을 테스트하던 테스트 코드들이 `test` 패키지에서 `common.service`에 존재하던 것을 `utility` 패키지의 추가로 인하여 `common.operation.service`로 이전하였습니다.
원서 삭제 시 원서의 접수 번호를 이용합니다
```
DELETE /utility/v3/oneseo?submitCode=A-1
```
다음과 같이 `submitCode` 쿼리파라미터 까지 전달한다면 `A-1` 원서를 삭제합니다.
회원 탈퇴 시 계정의 전화번호를 이용합니다
```
DELETE /utility/v3/member?phoneNumber=01012345678
```
다음과 같이 `phoneNumber` 쿼리파라미터를 전달한다면 해당하는 전화번호를 가진 계정과 계정의 원서,인증코드까지 삭제합니다.

[utility] 원서삭제 및 회원탈퇴 기능 구현

---

src/main/java/team/themoment/hellogsmv3/global/security/auth/service/OAuthAuthenticationService.java
src/test/java/team/themoment/hellogsmv3/domain/security/auth/service/OAuthAuthenticationServiceTest.java

- #243 에서 정의된 ``OAuthAuthenticationService`` 서비스 클래스의 테스트 코드를 작성하고 테스트 코드를 작성하면서 발견한 로직의 취약점을 보강하였습니다.
OAuth 인증/인가를 처리하는 서비스 클래스의 로직을 테스트하는 코드를 작성하였습니다
테스트 케이스는 다음과 같습니다
- 유효한 provider와 code가 주어지고 기존 회원이 존재하면 OAuth 인증을 완료하고 보안 컨텍스트에 인증 정보를 설정한다
- 유효한 provider와 code가 주어지고 신규 회원이면 새로운 회원을 생성하고 OAuth 인증을 완료한다
- 세션이 무효화된 상태에서 요청이 오면 새로운 세션을 생성하고 보안 컨텍스트를 설정한다
- 세션이 없는 상태에서 요청이 오면 새로운 세션을 생성하고 보안 컨텍스트를 설정한다
- 회원의 role이 null인 경우 기본 권한 UNAUTHENTICATED를 설정한다
또한 사용자의 `role`이 null 일 경우 `Map.of()`로 유저 정보를 구성하는 과정에서 NPE가 발생할 수 있는 취약점을 확인하여 방어 로직을 구현하였습니다

[auth] OAuthAuthenticationService 방어 로직 강화 및 테스트 코드 작성

---

src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java

세션 저장 시 `creationTime key must not be null` 문제를 해결하기 위하여 보안 설정에 `migrateSession `를 적용하였습니다
Spring Security에서 `creationTime key must not be null` 문제가 발생하였는데 이러한 문제를 해결하기 위하여 #263 에서 세션 저장 시 검증을 강화하도록 하였습니다.
해당 조치에 이어서 보안 설정에서 세션을 아예 새로 생성하도록 설정을 추가하였습니다.
해당 블로그를 참고하였습니다
- https://algorithm-master.tistory.com/174

[auth] 세션 관련 정책 설정 추가

---

src/main/java/team/themoment/hellogsmv3/global/security/auth/service/provider/KakaoOAuthProvider.java

Kakao OAuth 사용 시 사용자가 유효하지 않은 `email`을 갖고 있다면 `id`를 사용하도록 수정하였습니다
- #208 해당 PR에서 적용되었던 변경사항이
- #243 PR에서 OAuth 인증 로직이 대폭 변경되며 포함되지 않았었는데 해당 변경사항을 반영하였습니다.

[auth] Kakao OAuth 인증 과정 중 `email`유효하지 않을 시 `id` 사용

---

src/main/java/team/themoment/hellogsmv3/global/thirdParty/aws/sns/impl/SendCodeNotificationServiceImpl.java

4차 원서 작성 테스트 후 [선생님의 요구사항](https://www.notion.so/4-2025-08-28-25d3f725618580e38fe7fea4a97d96f6?source=copy_link)을 반영하여 본인인증 SMS 메세지의 본문을 변경하였습니다
기존에는 본인인증 SMS 메세지에서 본인이 요청하지 않았을 경우를 가정하여 알림성 메세지를 보내줄 때 다음과 같은 본문 내용으로 보내주었습니다
```
본인이 요청한게 아니라면 교무실 062-949-6843 으로 문의해주세요.
```
해당 내용을 선생님의 요구사항에 맞게 다음과 같이 수정하였습니다.
```
본인이 요청한 경우가 아니라면 교무실 062-949-6843 으로 문의해주세요.
```

[thirdParty] 본인인증 SMS 메세지 본문 변경

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/annotation/SubjectNameValidator.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/annotation/ValidSubjectName.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/controller/OneseoController.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/MiddleSchoolAchievementReqDto.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/OneseoReqDto.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/OneseoTempReqDto.java
src/test/java/team/themoment/hellogsmv3/domain/oneseo/annotation/SubjectNameValidatorTest.java

중복된 과목이름에 대한 유효성검사를 추가했습니다.
추가과목을 입력할 수 있는 기능 때문에, 같은 과목을 여러번 입력 할 수 있는 가능성이 있었습니다. 이를 해결하기 위해 중복된 과목 이름에 대해 유효성 검사를 추가했습니다.
MiddleSchoolAchievementReqDto의 generalSubjects, newSubjects, artsPhysicalSubjects는 각각 일반교과 과목, 추가교과 과목, 예체능 교과 과목을 나타내는 문자열 리스트입니다.
서로 하나라도 중복된 과목이름이 감지되면, Validator에서 "중복된 이름의 과목이 입력되었습니다."라는 메세지를 나타내도록 하였습니다.

[oneseo] 중복된 과목이름 유효성검사 추가

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/annotation/SubjectNameValidator.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/OneseoTempReqDto.java
src/test/java/team/themoment/hellogsmv3/domain/oneseo/annotation/SubjectNameValidatorTest.java

SubjectNameValidator에서 사용하는 값들이, null일때 발생하던 NPE를 해결했습니다.
원서 임시저장의 경우 과목명 필드가 채워지지 않았고 추가과목 필드는 추가과목이 없을시 null 입니다.
SubjectNameValidator에서도 null 값에 대한 예외처리가 없어 NPE가 발생했습니다.
임시저장시 Validation을 수행하지 않도록 하고, Validator에서도 필요한 필드가 null 인경우에 대한 예외처리를 추가했습니다.

[oneseo] 중복 과목명 validation에서 발생한 NPE 해결

---

src/main/java/team/themoment/hellogsmv3/global/security/auth/service/OAuthAuthenticationService.java
src/main/resources/application.yml
src/test/java/team/themoment/hellogsmv3/domain/security/auth/service/OAuthAuthenticationServiceTest.java

세션 만료 시간을 3시간으로 연장하였으며 기존에 서비스 코드에서 하드코딩된 세션 만료시간을 프로파일에서 주입받아 사용할 수 있도록 하였습니다
기존에 로그인 유지 시간이 짧다는 불만사항이 있어 이를 반영해 세션 만료시간을 3시간으로 연장하였습니다.`OAuthAuthenticationService`에서도 `@Value`어노테이션으로 프로파일의 ``spring.session.timeout`` 또는 ``server.servlet.session.timeout`` 프로퍼티의 값을 세션에 설정하도록 하였습니다

[auth] 세션 유지시간 연장

---

src/main/resources/application.yml

jpa의 open-in-view 옵션을 비활성화했습니다.
`open-in-view` 옵션은 JPA의 영속성 컨텍스트를 언제까지 유지할지에 대한 옵션으로, 기본값은 true입니다.
이 옵션이 true일 경우, Client의 요청이 끝날 때까지  영속성 컨텍스트가 유지되고, 커넥션이 db에 반환되지 않습니다.
@Transactional이 적용된 메서드를 빠져나온후에도 유지되므로, Thymeleaf, jsp같이 직접 view를 백엔드에서 정의하는 경우가 아니라면 false로 두어 커넥션이 바로 반환되도록 하는것이 바람직하다고 생각됩니다.
따라서 application.yml에서 해당 옵션을 비활성화 하였습니다.
---

[global] jpa의 open-in-view 옵션 비활성화

---

build.gradle
src/main/java/team/themoment/hellogsmv3/global/common/logging/LoggingFilter.java
src/main/java/team/themoment/hellogsmv3/global/common/response/ApiResponseWrapper.java
src/main/resources/application.yml

monitoring을 위해 actuator, micrometer를 설정하였습니다.
micrometer-registry-prometheus를 추가하였고, actuator에서 prometheus 엔드포인트를 개방하였습니다.
추가로 CommonApiResponse Wrapping과 Logging 대상에서 prometheus 엔드포인트를 제외하였습니다.

[global] Monitoring을 위한 actuator, micrometer 설정

---

DockerfileStage
build.gradle
src/main/resources/application.yml

Spring Session의 `creationTime key must not be null` 오류를 해결하기 위해 Spring Boot 버전을 업그레이드하였습니다.
해당 이슈는 Spring Session 라이브러리의 알려진 문제로, 관련 이슈가 https://github.com/spring-projects/spring-session/issues/3347 및 https://github.com/spring-projects/spring-session/issues/2021 에 등록되어 있습니다.
이전에 #264, #263 PR을 통해 세션 정책을 강화하고 설정 로직을 방어적으로 수정하였으나, 근본적인 원인이 라이브러리 자체에 있어 완전한 해결이 어려웠습니다. 이에 따라 문제가 해결된 버전으로 업그레이드하는 방식을 채택하였습니다.

[global] `Spring Boot`,`Spring Cloud` 버전 변경

---

src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java

`SecurityConfig` 클래스의 `DefaultAuthorizationCodeTokenResponseClient` 주입을 제거하였습니다.
#243 에서 OAuth 인증 인가 방식이 변경됨에 따라 `SecurityConfig` 클래스에서 주입되던 아래 Bean이 아무런 효과가 없는 설정이 되었습니다.
```java
@Bean
public OAuth2AccessTokenResponseClient<OAuth2AuthorizationCodeGrantRequest> accessTokenResponseClient() {
return new DefaultAuthorizationCodeTokenResponseClient();
}
```
`DefaultAuthorizationCodeTokenResponseClient`는 OAuth 2.0 Authorization Code Grant 방식에서 `Authorization Code`를 `Access Token`으로 교환하는 HTTP 요청을 처리하는 클라이언트입니다. 
구체적으로는 다음 작업을 수행합니다:
- OAuth 제공자의 Token Endpoint에 `Authorization Code`를 전송
- `client_id`, `client_secret`, `code`, `redirect_uri`, `grant_type` 등의 파라미터를 포함한 HTTP POST 요청 생성
- 응답을 파싱하여 Access Token과 Refresh Token을 획득
이 클라이언트는 Spring Security OAuth2 Login의 기본 필터 체인에서 자동으로 사용되며, OAuth …

[auth] 미사용 OAuth 관련 설정 Bean 주입 제거

---

build.gradle

사용되는 부분이 없는 JSON 직렬화/역직렬화 종속성을 제거하여습니다.
기존엔 중학교 성적 저장과 같은 부분에서 `GSON`,`Smart-JSON` 종속성을 사용하였기에 해당 종속성이 서버 애플리케이션에 포함되었지만 2025년 운영기간에선 `Jackson`만 사용하고 있기 때문에 불필요한 종속성이 된 2가지 종속성을 완전히 제거하였습니다.
---

[global] 미사용 JSON 직렬화 종속성 제거

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/DownloadExcelService.java
src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/DownloadExcelServiceTest.java

[해당 요구사항](https://discord.com/channels/942787694872899604/1163324601577771008/1422755306697523210)을 반영하였습니다.
`IOT`로 표현되던 `1지망`,`2지망`,`3지망` 셸의 값을 `IoT`로 변경해달라는 요청에 따라 `DownloadExcelService`를 수정하였습니다. `Major` Enum을 수정하는 방안도 검토 되었으나 Excel에서만 수정되는 것으로 수정 사항이 한정적인 것을 고려하여 해당 서비스에서 포맷팅 메서드를 통하도록 결정하였습니다.
---

[oneseo] 엑셀 시트 출력 시 `IOT`를 `IoT`로 표현하도록 수정
