themoment-team/hellogsm-server-25

build.gradle
src/main/java/team/themoment/hellogsmv3/global/exception/GlobalExceptionHandler.java
src/main/java/team/themoment/hellogsmv3/global/exception/error/ExpectedException.java
src/main/java/team/themoment/hellogsmv3/global/exception/error/HelloException.java
src/main/java/team/themoment/hellogsmv3/global/exception/model/ExceptionResponseEntity.java

exception, exceptionHandler를 추가하였습니다.
`global.exception` 페키지에 `ExpectedException`, `ExceptionResponseEntity`, `GlobalExceptionHandler`를 작성하였습니다.

[global] exception & exceptionHandler 추가

---

src/main/java/team/themoment/hellogsmv3/domain/auth/controller/AuthenticationController.java
src/main/java/team/themoment/hellogsmv3/domain/auth/dto/BasicAuthenticationDto.java
src/main/java/team/themoment/hellogsmv3/domain/auth/service/AuthenticationService.java
src/main/java/team/themoment/hellogsmv3/domain/auth/service/BringAuthenticationByIdQuery.java
src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java

회원 정보를 조회하는 기능을 추가하였습니다.
`authentication/v3/authentication/{authenticationId}`
어드민 권한을 가진 사용자가 authenticationId로 회원 정보를 조회하는 기능을 추가하였습니다.

add(auth): 회원 정보 조회 기능 추가

---

src/main/java/team/themoment/hellogsmv3/domain/auth/controller/AuthenticationController.java
src/main/java/team/themoment/hellogsmv3/domain/auth/dto/BasicAuthenticationDto.java
src/main/java/team/themoment/hellogsmv3/domain/auth/service/BringAuthenticationByIdQuery.java
src/main/java/team/themoment/hellogsmv3/domain/auth/service/QueryAuthenticationById.java
src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java

내 회원 정보를 조회하는 기능을 추가하였습니다.
`authentication/v3/authentication/me`
내 회원 정보를 조회하는 기능을 추가하였습니다.

add(auth): 내 회원 정보 조회 기능 추가

---

src/main/java/team/themoment/hellogsmv3/domain/application/controller/ApplicationController.java
src/main/java/team/themoment/hellogsmv3/domain/application/entity/abs/AbstractApplication.java
src/main/java/team/themoment/hellogsmv3/domain/application/service/UpdateFinalSubmissionService.java
src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java

내 원서 최종제출 상태 변경 기능을 개발하였습니다.
- `/application/v3/final-submit` 내 원서를 최종제출 상태로 변경합니다.
- 최종제출된 원서는 수정이 불가능합니다. (어드민은 가능)

[application] 최종제출 상태 변경

---

src/main/java/team/themoment/hellogsmv3/domain/applicant/dto/response/AdmissionTicketsResDto.java
src/main/java/team/themoment/hellogsmv3/domain/application/controller/ApplicationController.java
src/main/java/team/themoment/hellogsmv3/domain/application/entity/GraduatePersonalInformation.java
src/main/java/team/themoment/hellogsmv3/domain/application/entity/abs/AbstractApplication.java
src/main/java/team/themoment/hellogsmv3/domain/application/repo/ApplicationRepository.java
src/main/java/team/themoment/hellogsmv3/domain/application/service/QueryAdmissionTicketsService.java
src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java

수험표 출력 기능을 구현하였습니다.
`/application/v3/admission-tickets`경로로 요청을 하게되면 수험표 정보를 담은 리스트를 반환하게됩니다.

[application] 수험표 출력 기능 구현

---

src/main/java/team/themoment/hellogsmv3/domain/application/controller/ApplicationController.java
src/main/java/team/themoment/hellogsmv3/domain/application/service/DeleteApplicationByApplicantIdService.java
src/main/java/team/themoment/hellogsmv3/domain/application/service/DeleteApplicationByAuthIdService.java
src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java

내 원서 정보 삭제 기능을 구현하였습니다.
`DELETE /application/v3/application/me`로 요청을 하게되면 자신의 원서 정보를 삭제하게 됩니다.

[application] 내 원서 정보 삭제 기능 구현

---

build.gradle
src/main/java/team/themoment/hellogsmv3/HelloGsmV3Application.java
src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java
src/main/java/team/themoment/hellogsmv3/global/thirdParty/aws/s3/controller/S3Controller.java
src/main/java/team/themoment/hellogsmv3/global/thirdParty/aws/s3/properties/S3Environment.java
src/main/java/team/themoment/hellogsmv3/global/thirdParty/aws/s3/service/UploadImageService.java
src/main/resources/application.yml

이미지 업로드 기능을 구현하였습니다.
`/s3/v3/image`경로로 요청시 이미지를 s3에 업로드 하고 업로드된 파일의 url을 반환하게 됩니다.
엔드포인트가 좀 어색해보여서 더 좋은 이름의 엔드포인트가 생각나신다면 의견부탁드립니다.

[thirdParty] 이미지 업로드 기능 구현

---

src/main/java/team/themoment/hellogsmv3/domain/application/controller/ApplicationController.java

중복되는 컨트롤러 메서드를 제거하였습니다.
develop에 feature브랜치들 merge후에 컨트롤러에 중복되는 메서드가 발생해서 제거하였습니다.

[application] 중복되는 컨트롤러 메서드 제거

---

src/main/java/team/themoment/hellogsmv3/domain/member/controller/MemberController.java
src/main/java/team/themoment/hellogsmv3/domain/member/dto/FoundMemberResDto.java
src/main/java/team/themoment/hellogsmv3/domain/member/service/QueryMemberByIdService.java
src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java

지원자 정보 조회 기능을 구현하였습니다.
- `member/v3/member/me` client api 기능 구현
- `member/v3/member/{memberId}` admin api 기능 구현

[member] 지원자 정보 조회 기능 구현

---

src/main/java/team/themoment/hellogsmv3/domain/member/controller/MemberController.java
src/main/java/team/themoment/hellogsmv3/domain/member/dto/response/FoundMemberAuthInfoResDto.java
src/main/java/team/themoment/hellogsmv3/domain/member/service/QueryMemberAuthInfoByIdService.java
src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java

- 회원 정보 조회 기능을 구현
`자신의 회원 정보 조회 api`와 `회원 정보 조회 api`를 구현하였습니다.

[member] 회원 정보 조회 기능 구현

---

src/main/java/team/themoment/hellogsmv3/domain/member/controller/MemberController.java
src/main/java/team/themoment/hellogsmv3/domain/member/dto/request/ModifyMemberReqDto.java
src/main/java/team/themoment/hellogsmv3/domain/member/entity/Member.java
src/main/java/team/themoment/hellogsmv3/domain/member/service/ModifyMemberService.java
src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java

지원자 정보 수정 기능 구현하였습니다.
`PUT  /member/v3/member/me` api에서 사용하는 지원자 정보 수정 기능을 구현하였습니다.

[member] 지원자 정보 수정 기능 구현

---

src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java
src/main/java/team/themoment/hellogsmv3/global/thirdParty/aws/s3/controller/S3Controller.java

- 이미지 업로드 uri를 변경
이미지 업로드 uri를 변경하였습니다.
`/application/v3/image` -> `/oneseo/v3/image`

[thirdParty] 이미지 업로드 uri 변경

---

src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateMockScoreServiceTest.java

모의성적 계산 클래스의 서비스 로직 테스트코드를 추가하였습니다.
- 유효한 성적 데이터가 주어졌을 때
- 졸업예정자라면 -> CalculateGradeService를 호출
- 졸업자라면 -> CalculateGradeService를 호츌
- 검정고시 응시자라면 -> CalculateGedService를 호출

[oneseo] 모의성적 계산 서비스 로직 테스트코드 추가

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/response/AdmissionTicketsResDto.java
src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/QueryAdmissionTicketsServiceTest.java

수험표 출력 기능 테스트 코드 작성
1. 수험표 리스트를 반환한다

[oneseo] 수험표 출력 기능 테스트 코드 작성

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/DownloadExcelService.java

비즈니스 로직에 맞도록 엑셀 출력시 최종점수 계산식을 추가하였습니다.
1차전형 100점 > 50% 반영 50점
직무적성 100점 > 30% 반영 30점
면점 100점 > 20%반영 20점

[oneseo] 엑셀 출력 최종점수 계산식 추가

---

src/main/java/team/themoment/hellogsmv3/domain/member/service/MemberService.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/DownloadExcelService.java
src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/DownloadExcelServiceTest.java

엑셀 출력 기능 테스트코드 작성
1. 모든 전형의 시트를 생성하고 데이터를 채운다.

[oneseo] 엑셀 출력 기능 테스트코드 작성

---

src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/OneseoServiceTest.java

[oneseo] 원서 공통 서비스로직 테스트코드 추가

---

src/test/java/team/themoment/hellogsmv3/domain/member/service/MemberServiceTest.java

[member] 맴버 공통 서비스로직 테스트코드 추가

---

.github/workflows/hellogsm-stage-cd.yml
DockerfileStage
scripts/deploy.sh
scripts/dev-deploy.sh

stage 환경의 ci/cd flow를 도커를 사용하도록 변경하였습니다.
- stage 환경용 Dockerfile을 추가한 후 code deploy에서 Dockerfile을 빌드하여 spring application을 실행하도록 변경하였습니다.
- stage ec2 내부에는 mysql, redis 컨테이너가 실행 중 입니다.

[global] stage 환경 ci/cd flow 도커를 사용하도록 재구축

---

src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoServiceTest.java

#125 해당 PR에서 원서 수정 service 클래스의 수정사항이 테스트코드에 반영되지 않아 테스트케이스에서 실패하였습니다. 변경사항에 해당하는 부분을 수정하였습니다.

[oneseo] 원서 테스트코드 변경사항 수정

---

src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java
src/main/java/team/themoment/hellogsmv3/global/security/auth/AuthEnvironment.java
src/main/java/team/themoment/hellogsmv3/global/security/data/HeaderConstant.java
src/main/java/team/themoment/hellogsmv3/global/security/handler/CustomUrlAuthenticationSuccessHandler.java
src/main/resources/application.yml

로그인 성공시 `X-HG-ENV` 헤더 값에 따라 로컬 테스트 환경 url로 리다이렉트 되도록 변경하였습니다.
테스트를 진행할 마땅한 방법을 찾지 못해 테스트를 진행 해보지는 못하였습니다..

[global] 로컬 테스트 환경 리다이렉트 url 변경기능 추가

---

src/main/resources/logback-spring.xml

prod 환경 로그 수집 모니터링 환경을 구축하였습니다.
- `logback.xml` 파일에 prod profile일시 `hellogsm-prod-log` 로그그룹에 로그가 수집되도록 설정하였습니다.

[global] prod 환경 로그 수집 모니터링 환경 구축

---

src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoServiceTest.java

접수번호가 원서 생성시 할당되도록 변경되어 테스트코드를 수정하였습니다.

[test] 원서 생성시 할당되는 접수번호에 대한 테스트코드 수정

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/response/MockScoreResDto.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateGedService.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateGradeService.java

모의 성적 api response를 디자인에 맞게 변경하였습니다.

[oneseo] 모의 성적 api response 디자인에 맞게 변경

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateGedService.java

검정고시 환산 값 계산시 총 점수의 범위를 벗어나는 값을 입력에 대한 예외처리를 추가하였습니다.

[oneseo] 검정고시 총 점수의 범위를 벗어나는 값에 대한 예외처리

---

cloud-diagram.py

cloud-diagram as code로 작성하였습니다.
`diagrams` 패키지 사용하여 진행하였습니다.
레이아웃은 이쁘지 않아 추후 `Graphviz`통해서 가독성 향상시키면 좋을 거 같습니다.
https://diagrams.mingrammer.com/

Create Cloud Diagram

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateGedService.java

검정고시 환산 점수가 음수가 나온다면 0점 처리하도록 예외처리를 추가하였습니다.

[oneseo] 검정고시 환산 점수가 음수가 나온다면 0점 처리하도록 예외처리 추가

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/OneseoTempStorageService.java

원서 제출을 한 상태에서 원서 임시저장을 할 수 없게 변경하였습니다.

[oneseo] 이미 원서 제출을 하였다면 원서 임시저장을 할 수 없도록 변경

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/OneseoReqDto.java
src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoServiceTest.java
src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/OneseoServiceTest.java
src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/QueryOneseoByIdServiceTest.java

- #155 해당 PR에서 추가된 기능인 isValidMiddleSchoolInfo 메서드에 대한 테스트코드를 추가하였습니다. c6dc499607d39b4ef8660524933652687c9c0365
- 추가로 해당 메서드와 #157 해당 PR이 반영될때 테스트코드에 반영하지 않아 ci에 실패하여 해당 부분도 수정하였습니다. ab6487248b4d0a982dc5636f6459bac73eb83632

[oneseo] isValidMiddleSchoolInfo 메서드 관련 테스트코드 추가

---

src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoServiceTest.java
src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/OneseoServiceTest.java

#166 해당 PR에서 반영된 OneseoService의 접수번호 할당 메서드의 테스트코드를 추가하였습니다.

[oneseo] 접수번호 할당 메서드 테스트코드 추가

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/DownloadExcelService.java
src/main/resources/application.yml
src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/DownloadExcelServiceTest.java

원서 엑셀 출력시 Null 값인 필드가 있다면 NPE가 발생하여 모든 필드를 String으로 형변환하였습니다.

[oneseo] 원서 엑셀 출력시 필드 String으로 형변환

---

src/main/java/team/themoment/hellogsmv3/domain/common/date/controller/DateController.java
src/main/java/team/themoment/hellogsmv3/domain/member/controller/MemberController.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/OneseoReqDto.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/OneseoTempReqDto.java
src/main/java/team/themoment/hellogsmv3/global/config/SwaggerConfig.java
src/main/java/team/themoment/hellogsmv3/global/thirdParty/aws/sns/impl/SendCodeNotificationServiceImpl.java

`/date` API가 swagger 설정이 누락되어 추가하였습니다.
추가로 간단한 오타 수정을 함께하였습니다.

[global] date API swagger 설정 추가

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/custom/impl/CustomOneseoRepositoryImpl.java

1차 합격된 지원자만 수험표 출력에 필요한 row를 query하기 위해 where절에 조건을 추가하였습니다.
```java
where(entranceTestResult.firstTestPassYn.eq(YES))
```

[oneseo] 1차 합격 지원자만 수험표가 출력되도록 수정

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/Oneseo.java

tb_oneseo 테이블에 해당 원서의 합불여부 의미하는 pass_yn 컬럼을 추가하였습니다.

[oneseo] tb_oneseo 테이블에 pass_yn 컬럼 추가

---

src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/CalculateGradeServiceTest.java
src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoServiceTest.java
src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/QueryOneseoByIdServiceTest.java

#183 #181 해당 작업의 변경사항들에 대한 테스트코드를 수정하였습니다.

[oneseo] 예체능 개별학기 환산점, 원서 수정 관련 테스트코드 수정

---

src/main/java/team/themoment/hellogsmv3/HelloGsmV3Application.java
src/main/resources/application.yml

redis를 세션 스토리지로 사용한다는 것을 명시하는 어노테이션을 추가하였습니다.

[global] redis를 세션 스토리지 사용을 선언

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/event/handler/OneseoApplyEventHandler.java

현재 profile 정보를 받아오는 방식을 변경합니다.

[oneseo] 현재 profile 정보 받아오는 방식 변경

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/AptitudeEvaluationScoreReqDto.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/InterviewScoreReqDto.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyAptitudeEvaluationScoreService.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyInterviewScoreService.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/OneseoService.java

평가점수(인적성, 면점)를 service 단에서 validate 하지 않고 컨트롤러 단에서 validate 하기 위해 dto valid 어노테이션을 추가하였습니다.

[oneseo] 평가점수 dto valid 어노테이션으로 검증하도록 수정

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/AptitudeEvaluationScoreReqDto.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/InterviewScoreReqDto.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/event/handler/OneseoApplyEventHandler.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyAptitudeEvaluationScoreService.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyInterviewScoreService.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/OneseoService.java

v20241011.0

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/event/handler/OneseoApplyEventHandler.java
src/main/java/team/themoment/hellogsmv3/global/thirdParty/feign/client/dto/request/DiscordAlarmReqDto.java
src/main/java/team/themoment/hellogsmv3/global/thirdParty/feign/client/type/Channel.java

디스코드 알림 API의 스펙이 변경되어(채널 속성 추가) 반영하였습니다.

[oneseo] 변경된 디스코드 알림 API 스펙에 따라 채널 추가

---

src/main/java/team/themoment/hellogsmv3/global/common/handler/AuthenticationArgumentResolver.java
src/main/java/team/themoment/hellogsmv3/global/thirdParty/aws/sns/impl/SendCodeNotificationServiceImpl.java

인증번호를 포함한 문자 전송이 실패하여 템플릿을 간략화하였습니다. 추가로 교무실 전화번호를 변경하였습니다.

[global] HOTFIX 문자 전송 템플릿 간략화 및 수정

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoService.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/ModifyOneseoService.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/OneseoService.java
src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/OneseoServiceTest.java

전형(Screening)이 변경될때만 접수번호가 업데이트 되도록 변경

원서 접수번호 할당로직 변경

---

build.gradle
src/main/java/team/themoment/hellogsmv3/HelloGsmV3Application.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoService.java
src/main/java/team/themoment/hellogsmv3/global/security/oauth/CustomOauth2UserService.java

v20241017.0

---

src/main/java/team/themoment/hellogsmv3/domain/common/operation/controller/OperationTestResultController.java

operation api url에 오타가 있어 수정하였습니다.

[operation] operation api url 수정

---

src/main/java/team/themoment/hellogsmv3/domain/common/operation/controller/OperationTestResultController.java
src/main/java/team/themoment/hellogsmv3/global/security/SecurityConfig.java

v20241021.1

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/response/AdmissionTicketsResDto.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/entity/Oneseo.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/custom/impl/CustomOneseoRepositoryImpl.java
src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/QueryAdmissionTicketsServiceTest.java

수험표 출력 관련 요구사항으로 API 스펙을 수정하였습니다.
- 수험표 출력시 "전형" 필드를 삭제하였습니다.
- "수험번호" (`examinationNumber`) 필드가 추가되었습니다.

[oneseo] 수험표 출력 API 스펙 변경

---

src/main/java/team/themoment/hellogsmv3/domain/common/testResult/service/QueryTestResultService.java

FE의 측의 요구사항으로 2차 전형 결과 확인 API 반환값에 1차 전형 결과도 포함되도록 변경

[test-result] 요구사항 변경으로 2차 전형 결과 API 반환값 수정

---

.github/workflows/hellogsm-prod-cd.yml
.github/workflows/hellogsm-prod-ci.yml
.github/workflows/hellogsm-stage-cd.yml
.github/workflows/hellogsm-stage-ci.yml

stage, prod 브랜치에 pr, push event가 발생할때 실행되는 CI script 작성하였습니다.
`./gradlew build`가 아닌 `./gradlew assemble` 명령어를 사용해 패키징을 제외하고 테스트와 컴파일만 되도록 하였습니다.
저는 패키징이 불필요할거 같아 제외하였는데 의견 부탁드립니다!

[CI] stage, prod 환경 CI script 작성

---

DockerfileStage
cloud-diagram.py
settings.gradle
src/main/java/team/themoment/hellogsmv3/global/config/SwaggerConfig.java

[다음 변경사항](https://discord.com/channels/942787694872899604/991124850112471041/1410169135551352894)에 따라 프로젝트명을 `hellogsm-server-25`로 변경하고 필요한 변경점들을 적용하였습니다
프로젝트명이 변경됨에 따라 Swagger,Dockerfile,Gradle 설정 및 Python 클라우드 아키택쳐에서 프로젝트명 변경을 반영하였습니다
추가적으로 변경이 필요한 부분이 있는지 점검해주시면 감사하겠습니다

[global] 레포지터리명 변경에 따른 프로젝트명 변경

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/annotation/DesiredMajorsValidator.java
src/test/java/team/themoment/hellogsmv3/domain/oneseo/annotation/DesiredMajorsValidatorTest.java

DesiredMajorsValidator 클래스의 테스트 코드를 작성하였습니다
1지망,2지망,3지망 전공이 중복되지는 않는지 검증하는 클래스 DesiredMajorsValidator의 테스트 코드를 작성했습니다,
테스트 케이스는 다음과 같습니다
- 모든 전공이 서로 다른 경우 (SW, AI, IOT)
- 첫 번째 전공이 null인 경우
- 두 번째 전공이 null인 경우
- 세 번째 전공이 null인 경우
- 모든 전공이 null인 경우
- 1지망과 2지망이 중복된 경우
- 1지망과 3지망이 중복된 경우
- 2지망과 3지망이 중복된 경우
- 모든 지망이 동일한 경우

[oneseo] DesiredMajorsValidator 클래스 테스트 코드 작성

---

README.md

프로젝트에서 누락되어 있던 `README`를 작성하여 추가하였습니다.
https://github.com/themoment-team/hellogsm-front-25 레포지터리의 `README`를 참고하였으며 마크다운으로 작성하였습니다.
---

[global] README 추가

---

src/main/java/team/themoment/hellogsmv3/domain/oneseo/repository/custom/impl/CustomOneseoRepositoryImpl.java
src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/DownloadExcelService.java
src/test/java/team/themoment/hellogsmv3/domain/oneseo/service/DownloadExcelServiceTest.java

`DownloadExcelService`에서 접수 번호 포맷팅,정렬 등의 요구사항을 반영하였습니다.
`DownloadExcelService`에서 접수 번호 포맷팅을 제거하였으며 `A-1`,`B-1`과 같은 형식으로 엑셀 표기를 하도록 개선하였습니다.또한 접수번호에 따라 오름차순 정렬이 적용되도록 수정하였습니다.
---

[oneseo] Excel 출력 서비스에서 접수 번호 관련 요구사항 반영
